//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvAutoPolNoGenerationItem
    {
        public int advautopolno_id { get; set; }
        public string advautopolno_prefix { get; set; }
        public string advautopolno_suffix { get; set; }
        public Nullable<int> advautopolno_branch { get; set; }
        public Nullable<int> advautopolno_brokerRep { get; set; }
        public Nullable<int> advautopolno_cob { get; set; }
        public Nullable<int> advautopolno_insurer { get; set; }
        public Nullable<int> advautopolno_salesTeam { get; set; }
        public Nullable<int> advautopolno_serviceTeam { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
