//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnzsicCode
    {
        public int anz_id { get; set; }
        public string anz_code { get; set; }
        public string anz_name { get; set; }
        public string anz_created_who { get; set; }
        public System.DateTime anz_created_when { get; set; }
        public string anz_updated_who { get; set; }
        public Nullable<System.DateTime> anz_updated_when { get; set; }
        public string anz_desc { get; set; }
        public bool anz_inactive { get; set; }
        public Nullable<bool> Anz_Farm { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
