//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class balance
    {
        public int bal_tran_id { get; set; }
        public int bal_entity_id { get; set; }
        public int bal_led_id { get; set; }
        public decimal bal_amount { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual entity entity { get; set; }
        public virtual gl_ledgers gl_ledgers { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
