//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerFeeDefault
    {
        public int bfd_id { get; set; }
        public int bfd_branchId { get; set; }
        public int bfd_brokerRepId { get; set; }
        public int bfd_classOfBusinessId { get; set; }
        public int bfd_newBusinessWorkbookTypeId { get; set; }
        public int bfd_renewalWorkbookTypeId { get; set; }
        public int bfd_renewalTransferWorkbookTypeId { get; set; }
        public int bfd_positiveEndorsementWorkbookTypeId { get; set; }
        public int bfd_negativeEndorsementWorkbookTypeId { get; set; }
        public int bfd_cancellationWorkbookTypeId { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual BrokerFeeDefaultWorkbookType BrokerFeeDefaultWorkbookType { get; set; }
        public virtual BrokerFeeDefaultWorkbookType BrokerFeeDefaultWorkbookType1 { get; set; }
        public virtual BrokerFeeDefaultWorkbookType BrokerFeeDefaultWorkbookType2 { get; set; }
        public virtual BrokerFeeDefaultWorkbookType BrokerFeeDefaultWorkbookType3 { get; set; }
        public virtual BrokerFeeDefaultWorkbookType BrokerFeeDefaultWorkbookType4 { get; set; }
        public virtual BrokerFeeDefaultWorkbookType BrokerFeeDefaultWorkbookType5 { get; set; }
    }
}
