//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerFeeDefaultWorkbookType
    {
        public BrokerFeeDefaultWorkbookType()
        {
            this.BrokerFeeDefaults = new HashSet<BrokerFeeDefault>();
            this.BrokerFeeDefaults1 = new HashSet<BrokerFeeDefault>();
            this.BrokerFeeDefaults2 = new HashSet<BrokerFeeDefault>();
            this.BrokerFeeDefaults3 = new HashSet<BrokerFeeDefault>();
            this.BrokerFeeDefaults4 = new HashSet<BrokerFeeDefault>();
            this.BrokerFeeDefaults5 = new HashSet<BrokerFeeDefault>();
        }
    
        public int bfdwt_id { get; set; }
        public bool bfdwt_auto { get; set; }
        public decimal bfdwt_percentage { get; set; }
        public int bfdwt_basisId { get; set; }
        public decimal bfdwt_default { get; set; }
        public decimal bfdwt_minimum { get; set; }
        public decimal bfdwt_maximum { get; set; }
        public bool bfdwt_amend { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<BrokerFeeDefault> BrokerFeeDefaults { get; set; }
        public virtual ICollection<BrokerFeeDefault> BrokerFeeDefaults1 { get; set; }
        public virtual ICollection<BrokerFeeDefault> BrokerFeeDefaults2 { get; set; }
        public virtual ICollection<BrokerFeeDefault> BrokerFeeDefaults3 { get; set; }
        public virtual ICollection<BrokerFeeDefault> BrokerFeeDefaults4 { get; set; }
        public virtual ICollection<BrokerFeeDefault> BrokerFeeDefaults5 { get; set; }
    }
}
