//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancellation_reason
    {
        public int cancreas_id { get; set; }
        public string cancreas_created_who { get; set; }
        public System.DateTime cancreas_created_when { get; set; }
        public string cancreas_updated_who { get; set; }
        public Nullable<System.DateTime> cancreas_updated_when { get; set; }
        public string cancreas_name { get; set; }
        public string cancreas_desc { get; set; }
        public bool cancreas_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
