//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cash_receipts
    {
        public cash_receipts()
        {
            this.cash_receipt_application = new HashSet<cash_receipt_application>();
        }
    
        public int rcpt_id { get; set; }
        public Nullable<int> rcpt_tran_id { get; set; }
        public string rcpt_paymeth { get; set; }
        public string rcpt_cheque_no { get; set; }
        public string rcpt_name { get; set; }
        public string rcpt_bank { get; set; }
        public string rcpt_branch { get; set; }
        public string rcpt_cardno { get; set; }
        public string rcpt_cardholder { get; set; }
        public Nullable<System.DateTime> rcpt_expiry { get; set; }
        public string rcpt_auth { get; set; }
        public string rcpt_amexsec { get; set; }
        public Nullable<int> rcpt_banking_id { get; set; }
        public Nullable<int> rcpt_parent_id { get; set; }
        public Nullable<decimal> rcpt_amount { get; set; }
        public string rcpt_remarks { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual banking banking { get; set; }
        public virtual ICollection<cash_receipt_application> cash_receipt_application { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
