//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetails_Category5
    {
        public ClientDetails_Category5()
        {
            this.entities = new HashSet<entities>();
        }
    
        public int cdcat5_id { get; set; }
        public string cdcat5_created_who { get; set; }
        public System.DateTime cdcat5_created_when { get; set; }
        public string cdcat5_updated_who { get; set; }
        public Nullable<System.DateTime> cdcat5_updated_when { get; set; }
        public string cdcat5_name { get; set; }
        public string cdcat5_desc { get; set; }
        public bool cdcat5_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<entities> entities { get; set; }
    }
}
