//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_methods
    {
        public contact_methods()
        {
            this.claim_tasks = new HashSet<claim_tasks>();
            this.journals = new HashSet<journal>();
            this.tasks = new HashSet<task>();
        }
    
        public int conmet_id { get; set; }
        public string conmet_created_who { get; set; }
        public System.DateTime conmet_created_when { get; set; }
        public string conmet_updated_who { get; set; }
        public Nullable<System.DateTime> conmet_updated_when { get; set; }
        public string conmet_name { get; set; }
        public string conmet_desc { get; set; }
        public bool conmet_inactive { get; set; }
        public Nullable<bool> conmet_default { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<claim_tasks> claim_tasks { get; set; }
        public virtual ICollection<journal> journals { get; set; }
        public virtual ICollection<task> tasks { get; set; }
    }
}
