//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEFTPredefinedError
    {
        public DEFTPredefinedError()
        {
            this.DEFTItemsInError_Predefined = new HashSet<DEFTItemsInError_Predefined>();
        }
    
        public int deftpe_id { get; set; }
        public string deftpe_description { get; set; }
        public string deftpe_short_description { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<DEFTItemsInError_Predefined> DEFTItemsInError_Predefined { get; set; }
    }
}
