//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEFTStatementId
    {
        public int deftent_id { get; set; }
        public int deftent_ent_id { get; set; }
        public short deftent_highest_statement_id { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual entity entity { get; set; }
    }
}
