//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public int et_id { get; set; }
        public string et_name { get; set; }
        public string et_description { get; set; }
        public string et_created_who { get; set; }
        public Nullable<System.DateTime> et_created_when { get; set; }
        public string et_updated_who { get; set; }
        public Nullable<System.DateTime> et_updated_when { get; set; }
        public int et_sharing { get; set; }
        public Nullable<int> et_branch { get; set; }
        public string et_blob_pointer { get; set; }
        public byte[] RowVersion { get; set; }
        public bool et_inactive { get; set; }
    }
}
