//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_ins_transaction_types
    {
        public gen_ins_transaction_types()
        {
            this.policy_transaction_documents = new HashSet<policy_transaction_documents>();
            this.workbooks = new HashSet<workbook>();
            this.policies = new HashSet<policy>();
            this.soa_classes_of_business = new HashSet<soa_classes_of_business>();
        }
    
        public int gentrans_id { get; set; }
        public string gentrans_created_who { get; set; }
        public System.DateTime gentrans_created_when { get; set; }
        public string gentrans_updated_who { get; set; }
        public Nullable<System.DateTime> gentrans_updated_when { get; set; }
        public string gentrans_name { get; set; }
        public string gentrans_desc { get; set; }
        public bool gentrans_inactive { get; set; }
        public Nullable<short> gentrans_current { get; set; }
        public string gentrans_abbreviation { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<policy_transaction_documents> policy_transaction_documents { get; set; }
        public virtual ICollection<workbook> workbooks { get; set; }
        public virtual ICollection<policy> policies { get; set; }
        public virtual ICollection<soa_classes_of_business> soa_classes_of_business { get; set; }
    }
}
