//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_ins_classes_of_business
    {
        public gen_ins_classes_of_business()
        {
            this.class_of_business = new HashSet<class_of_business>();
            this.documentmappings = new HashSet<documentmapping>();
            this.general_insurance = new HashSet<general_insurance>();
            this.soa_classes_of_business = new HashSet<soa_classes_of_business>();
            this.iclose_products = new HashSet<iclose_products>();
        }
    
        public int gencob_id { get; set; }
        public string gencob_created_who { get; set; }
        public System.DateTime gencob_created_when { get; set; }
        public string gencob_updated_who { get; set; }
        public Nullable<System.DateTime> gencob_updated_when { get; set; }
        public string gencob_name { get; set; }
        public string gencob_desc { get; set; }
        public bool gencob_inactive { get; set; }
        public Nullable<int> gencob_category { get; set; }
        public string gencob_class_code { get; set; }
        public string gencob_class_code_2 { get; set; }
        public string gencob_class_code_3 { get; set; }
        public Nullable<int> gencob_apra_cob { get; set; }
        public Nullable<int> gencob_classification { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual apra_class_of_business apra_class_of_business { get; set; }
        public virtual ICollection<class_of_business> class_of_business { get; set; }
        public virtual class_of_business_classification class_of_business_classification { get; set; }
        public virtual ICollection<documentmapping> documentmappings { get; set; }
        public virtual ICollection<general_insurance> general_insurance { get; set; }
        public virtual ICollection<soa_classes_of_business> soa_classes_of_business { get; set; }
        public virtual ICollection<iclose_products> iclose_products { get; set; }
    }
}
