//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_rules
    {
        public int glr_id { get; set; }
        public string glr_glrs_set { get; set; }
        public int glr_glac_num { get; set; }
        public string glr_gle_name { get; set; }
        public bool glr_dr_cr { get; set; }
        public string glr_glamt_code { get; set; }
        public string glr_created_who { get; set; }
        public System.DateTime glr_created_when { get; set; }
        public string glr_updated_who { get; set; }
        public Nullable<System.DateTime> glr_updated_when { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual gl_accounts gl_accounts { get; set; }
        public virtual gl_rule_sets gl_rule_sets { get; set; }
        public virtual gl_sl_entities gl_sl_entities { get; set; }
    }
}
