//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLSl_Balances
    {
        public int Glac_num { get; set; }
        public string Glac_name { get; set; }
        public int Glac_Type { get; set; }
        public Nullable<int> Glsl_id { get; set; }
        public string Glsl_name { get; set; }
        public Nullable<decimal> Glsl_balance { get; set; }
        public Nullable<int> Spid { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
