//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class iclose_products
    {
        public int iclosepro_id { get; set; }
        public string iclosepro_created_who { get; set; }
        public System.DateTime iclosepro_created_when { get; set; }
        public string iclosepro_updated_who { get; set; }
        public Nullable<System.DateTime> iclosepro_updated_when { get; set; }
        public int iclosepro_parent_id { get; set; }
        public int iclosepro_cob_id { get; set; }
        public string iclosepro_name { get; set; }
        public string iclosepro_desc { get; set; }
        public bool iclosepro_inactive { get; set; }
        public string iclosepro_product_code { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual gen_ins_classes_of_business gen_ins_classes_of_business { get; set; }
        public virtual iclose_insurers iclose_insurers { get; set; }
    }
}
