//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class policy_task_status_types
    {
        public policy_task_status_types()
        {
            this.journals = new HashSet<journals>();
        }
    
        public int poltst_id { get; set; }
        public string poltst_created_who { get; set; }
        public System.DateTime poltst_created_when { get; set; }
        public string poltst_updated_who { get; set; }
        public Nullable<System.DateTime> poltst_updated_when { get; set; }
        public string poltst_name { get; set; }
        public string poltst_desc { get; set; }
        public bool poltst_inactive { get; set; }
        public bool poltst_closed { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<journals> journals { get; set; }
    }
}
