//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class policies_monthly
    {
        public int polmon_pol_id { get; set; }
        public int polmon_wor_id { get; set; }
        public Nullable<int> polmon_installment_no { get; set; }
        public Nullable<int> polmon_installment_index { get; set; }
        public Nullable<int> polmon_genins_id { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
