//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile_referrer
    {
        public profile_referrer()
        {
            this.profiles = new HashSet<profile>();
        }
    
        public int profref_id { get; set; }
        public string profref_created_who { get; set; }
        public System.DateTime profref_created_when { get; set; }
        public string profref_updated_who { get; set; }
        public Nullable<System.DateTime> profref_updated_when { get; set; }
        public string profref_name { get; set; }
        public string profref_desc { get; set; }
        public bool profref_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<profile> profiles { get; set; }
    }
}
