//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class related_entity_types
    {
        public related_entity_types()
        {
            this.related_entities = new HashSet<related_entities>();
        }
    
        public int relentty_id { get; set; }
        public string relentty_created_who { get; set; }
        public System.DateTime relentty_created_when { get; set; }
        public string relentty_updated_who { get; set; }
        public Nullable<System.DateTime> relentty_updated_when { get; set; }
        public string relentty_name { get; set; }
        public string relentty_desc { get; set; }
        public bool relentty_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<related_entities> related_entities { get; set; }
    }
}
