//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class soa_classes_of_business
    {
        public int soacob_id { get; set; }
        public string soacob_created_who { get; set; }
        public System.DateTime soacob_created_when { get; set; }
        public string soacob_updated_who { get; set; }
        public Nullable<System.DateTime> soacob_updated_when { get; set; }
        public string soacob_name { get; set; }
        public string soacob_desc { get; set; }
        public bool soacob_inactive { get; set; }
        public Nullable<int> soacob_class_of_business { get; set; }
        public Nullable<int> soacob_transaction_type { get; set; }
        public Nullable<int> soacob_soa_document { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual gen_ins_classes_of_business gen_ins_classes_of_business { get; set; }
        public virtual gen_ins_transaction_types gen_ins_transaction_types { get; set; }
        public virtual policy_transaction_documents policy_transaction_documents { get; set; }
    }
}
