//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sunrise_mapping
    {
        public int sunmap_id { get; set; }
        public string sunmap_created_who { get; set; }
        public System.DateTime sunmap_created_when { get; set; }
        public string sunmap_updated_who { get; set; }
        public Nullable<System.DateTime> sunmap_updated_when { get; set; }
        public string sunmap_name { get; set; }
        public string sunmap_desc { get; set; }
        public bool sunmap_inactive { get; set; }
        public string sunmap_local_name { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
