//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sunrise_workbooks
    {
        public long sunwor_id { get; set; }
        public Nullable<int> sunwor_parent_id { get; set; }
        public Nullable<System.DateTime> sunwor_lastsavedon { get; set; }
        public string sunwor_contractstage { get; set; }
        public string sunwor_contractstatus { get; set; }
        public string sunwor_processstatus { get; set; }
        public string sunwor_closetype { get; set; }
        public string sunwor_supplierid { get; set; }
        public string sunwor_productid { get; set; }
        public string sunwor_reference_no { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual workbook workbook { get; set; }
    }
}
