//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfigOption
    {
        public int nSystemConfigOptionId { get; set; }
        public string strOption { get; set; }
        public string strOptionId { get; set; }
        public byte[] sco_EncryptKey { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
