//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tables
    {
        public tables()
        {
            this.columns = new HashSet<columns>();
            this.transaction_set_items = new HashSet<transaction_set_items>();
        }
    
        public int tab_id { get; set; }
        public string tab_created_who { get; set; }
        public System.DateTime tab_created_when { get; set; }
        public string tab_updated_who { get; set; }
        public Nullable<System.DateTime> tab_updated_when { get; set; }
        public string tab_name { get; set; }
        public string tab_desc { get; set; }
        public int tab_sort { get; set; }
        public bool tab_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<columns> columns { get; set; }
        public virtual ICollection<transaction_set_items> transaction_set_items { get; set; }
    }
}
