//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webclient_master_list
    {
        public int ent_id { get; set; }
        public string ent_name { get; set; }
        public string ent_contact { get; set; }
        public string ent_telephone { get; set; }
        public string ent_suburb { get; set; }
        public string sta_name { get; set; }
        public string ent_postcode { get; set; }
        public string ent_address_1 { get; set; }
        public string ent_address_2 { get; set; }
        public string ent_address_3 { get; set; }
        public bool ent_status { get; set; }
        public Nullable<int> prof_service_team { get; set; }
        public Nullable<int> prof_sales_team { get; set; }
        public Nullable<int> prof_sub_agent { get; set; }
        public string sertea_name { get; set; }
        public string saltea_name { get; set; }
        public Nullable<int> prof_area { get; set; }
        public string sub_agent_name { get; set; }
        public Nullable<int> ent_roles { get; set; }
        public Nullable<decimal> pol_total_gross_premium { get; set; }
        public Nullable<int> genins_id { get; set; }
        public Nullable<int> prof_source_of_business { get; set; }
        public Nullable<int> prof_branch { get; set; }
        public int spid { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
