//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workbook_SOA
    {
        public int ws_id { get; set; }
        public Nullable<int> ws_parent_id { get; set; }
        public string ws_created_who { get; set; }
        public System.DateTime ws_created_when { get; set; }
        public string ws_updated_who { get; set; }
        public Nullable<System.DateTime> ws_updated_when { get; set; }
        public string ws_blob_pointer_scopeofadvice { get; set; }
        public string ws_blob_pointer_recommendations { get; set; }
        public string ws_blob_pointer_notice1 { get; set; }
        public string ws_blob_pointer_notice2 { get; set; }
        public string ws_blob_pointer_notice3 { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual workbook workbook { get; set; }
    }
}
