//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class workbooks
    {
        public workbooks()
        {
            this.atura_tagvalue = new HashSet<atura_tagvalue>();
            this.general_insurance1 = new HashSet<general_insurance>();
            this.ICloseWorkbookHeader = new HashSet<ICloseWorkbookHeader>();
            this.policies = new HashSet<policies>();
            this.sunrise_instalment = new HashSet<sunrise_instalment>();
            this.sunrise_workbooks = new HashSet<sunrise_workbooks>();
            this.Workbook_Notes = new HashSet<Workbook_Notes>();
            this.Workbook_SOA = new HashSet<Workbook_SOA>();
        }
    
        public int wor_id { get; set; }
        public int wor_parent_id { get; set; }
        public string wor_created_who { get; set; }
        public System.DateTime wor_created_when { get; set; }
        public string wor_updated_who { get; set; }
        public Nullable<System.DateTime> wor_updated_when { get; set; }
        public Nullable<int> wor_duration { get; set; }
        public bool wor_closed { get; set; }
        public string wor_contact { get; set; }
        public Nullable<int> wor_source_of_business { get; set; }
        public Nullable<int> wor_transaction_type { get; set; }
        public Nullable<int> wor_workbook { get; set; }
        public string wor_notes { get; set; }
        public Nullable<bool> wor_is_hidden { get; set; }
        public Nullable<decimal> wor_pol_total_gross_premium { get; set; }
        public Nullable<decimal> wor_terrorism_levy { get; set; }
        public string wor_invoice_comments { get; set; }
        public bool wor_DetailsCopied { get; set; }
        public byte[] RowVersion { get; set; }
        public string wor_other_parties { get; set; }
        public Nullable<System.DateTime> wor_date_effective { get; set; }
        public Nullable<System.DateTime> wor_date_from { get; set; }
        public Nullable<System.DateTime> wor_date_to { get; set; }
        public Nullable<decimal> wor_sum_insured { get; set; }
        public string wor_insured { get; set; }
        public Nullable<decimal> wor_total_base_premium { get; set; }
        public Nullable<decimal> wor_total_levies { get; set; }
        public Nullable<decimal> wor_total_duties { get; set; }
        public Nullable<decimal> wor_total_fees { get; set; }
        public Nullable<decimal> wor_total_commission { get; set; }
        public Nullable<decimal> wor_comm_net_gst { get; set; }
        public Nullable<decimal> wor_comm_gst { get; set; }
        public Nullable<decimal> wor_total_net_premium { get; set; }
        public Nullable<decimal> wor_base_premium { get; set; }
        public Nullable<decimal> wor_uw_fee { get; set; }
        public Nullable<decimal> wor_uw_fee_net_gst { get; set; }
        public Nullable<decimal> wor_uw_fee_gst { get; set; }
        public Nullable<decimal> wor_fee_gst { get; set; }
        public Nullable<decimal> wor_fee_net_gst { get; set; }
        public Nullable<decimal> wor_insurer_gst { get; set; }
        public Nullable<int> wor_insurer { get; set; }
        public Nullable<long> wor_hvi_value { get; set; }
        public Nullable<int> wor_limited_exemption { get; set; }
        public Nullable<int> wor_exemption_type { get; set; }
        public string wor_cover_note_number { get; set; }
        public string wor_location { get; set; }
        public string wor_policy_number { get; set; }
        public Nullable<int> wor_sub_agent { get; set; }
        public Nullable<decimal> wor_sub_agent_comm_payable { get; set; }
        public Nullable<decimal> wor_sub_agent_comm_payable_gst { get; set; }
        public Nullable<decimal> wor_sub_agent_comm_pay_net_gst { get; set; }
        public Nullable<decimal> wor_sub_agent_fee_payable { get; set; }
        public Nullable<decimal> wor_sub_agent_fee_payable_gst { get; set; }
        public Nullable<decimal> wor_sub_agent_fee_pay_net_gst { get; set; }
    
        public virtual ICollection<atura_tagvalue> atura_tagvalue { get; set; }
        public virtual entities entities { get; set; }
        public virtual entities entities1 { get; set; }
        public virtual exemption_types exemption_types { get; set; }
        public virtual gen_ins_transaction_types gen_ins_transaction_types { get; set; }
        public virtual general_insurance general_insurance { get; set; }
        public virtual ICollection<general_insurance> general_insurance1 { get; set; }
        public virtual general_insurance_workbooks general_insurance_workbooks { get; set; }
        public virtual ICollection<ICloseWorkbookHeader> ICloseWorkbookHeader { get; set; }
        public virtual limited_exemptions limited_exemptions { get; set; }
        public virtual ICollection<policies> policies { get; set; }
        public virtual sources_of_business sources_of_business { get; set; }
        public virtual ICollection<sunrise_instalment> sunrise_instalment { get; set; }
        public virtual ICollection<sunrise_workbooks> sunrise_workbooks { get; set; }
        public virtual ICollection<Workbook_Notes> Workbook_Notes { get; set; }
        public virtual ICollection<Workbook_SOA> Workbook_SOA { get; set; }
        public virtual WorkbookHeader WorkbookHeader { get; set; }
    }
}
