-- Mandatory fields
-- Document : https://steadfastgroup.sharepoint.com/teams/it/projects/boa/_layouts/15/WopiFrame2.aspx?sourcedoc={32549F3B-EC44-4E56-8D03-C4881AF2CE22}&file=BOA_Eclipse_Data_Conversion.docx&action=default
-- Section  : 4.7

UPDATE dbo.mandatory_fields SET mandf_field_name = 'BankDetails' WHERE mandf_field_name = 'all_bank_details'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'ABN' WHERE mandf_field_name = 'ent_abn'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'AddressLine1' WHERE mandf_field_name = 'ent_address_1'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Addressee' WHERE mandf_field_name = 'ent_addressee'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'BrokerReps' WHERE mandf_field_name = 'ent_BrokerReps'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Contact' WHERE mandf_field_name = 'ent_contact'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Email' WHERE mandf_field_name = 'ent_email'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Fax' WHERE mandf_field_name = 'ent_facsimile'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'JobTitle' WHERE mandf_field_name = 'ent_job_title'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Mobile' WHERE mandf_field_name = 'ent_mobile'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Postcode' WHERE mandf_field_name = 'ent_postcode'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Salutation' WHERE mandf_field_name = 'ent_salutation'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'StateId' WHERE mandf_field_name = 'ent_state'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Suburb' WHERE mandf_field_name = 'ent_suburb'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Telephone' WHERE mandf_field_name = 'ent_telephone'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Telephone2' WHERE mandf_field_name = 'ent_telephone_2'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'TradingAs' WHERE mandf_field_name = 'ent_trading_as'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Web' WHERE mandf_field_name = 'ent_web_site'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'AccountTypeId' WHERE mandf_field_name = 'prof_account_type'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'ACN' WHERE mandf_field_name = 'prof_acn'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'AnnualTurnover' WHERE mandf_field_name = 'prof_annual_turnover'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'AreaId' WHERE mandf_field_name = 'prof_area'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'BranchId' WHERE mandf_field_name = 'prof_branch'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'ClassificationId' WHERE mandf_field_name = 'prof_classification'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'NumDependants' WHERE mandf_field_name = 'prof_dependants'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'Employer' WHERE mandf_field_name = 'prof_employer'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'IndustryId' WHERE mandf_field_name = 'prof_industry'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'NatureOfBusiness' WHERE mandf_field_name = 'prof_nature_of_business'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'NumEmployees' WHERE mandf_field_name = 'prof_number_of_employees'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'OccupationId' WHERE mandf_field_name = 'prof_occupation'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'ReferrerId' WHERE mandf_field_name = 'prof_referrer'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'SalesTeamId' WHERE mandf_field_name = 'prof_sales_team'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'ServiceTeamId' WHERE mandf_field_name = 'prof_service_team'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'SourceOfBusinessId' WHERE mandf_field_name = 'prof_source_of_business'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'SpouseDateOfBirth' WHERE mandf_field_name = 'prof_spouses_DOB'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'SpouseName' WHERE mandf_field_name = 'prof_spouses_name'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'StatusId' WHERE mandf_field_name = 'prof_status'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'StructureId' WHERE mandf_field_name = 'prof_structure'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'UsualDebtorId' WHERE mandf_field_name = 'prof_usual_debtor'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'DateOfBirth' WHERE mandf_field_name = 'prof_year_commenced'
UPDATE dbo.mandatory_fields SET mandf_field_name = 'YearEstablished' WHERE mandf_field_name = 'prof_year_established'