//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_journal_items
    {
        public int glji_id { get; set; }
        public int glji_glj_id { get; set; }
        public int glji_glsl_id { get; set; }
        public decimal glji_amount { get; set; }
        public string glji_notes { get; set; }
        public string glji_created_who { get; set; }
        public Nullable<System.DateTime> glji_created_when { get; set; }
        public string glji_updated_who { get; set; }
        public Nullable<System.DateTime> glji_updated_when { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual gl_journal gl_journal { get; set; }
        public virtual gl_sub_ledgers gl_sub_ledgers { get; set; }
    }
}
