//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_journal
    {
        public gl_journal()
        {
            this.gl_journal_items = new HashSet<gl_journal_items>();
        }
    
        public int glj_id { get; set; }
        public Nullable<System.DateTime> glj_date { get; set; }
        public string glj_created_who { get; set; }
        public Nullable<System.DateTime> glj_created_when { get; set; }
        public string glj_updated_who { get; set; }
        public Nullable<System.DateTime> glj_updated_when { get; set; }
        public Nullable<int> glj_csh_id { get; set; }
        public Nullable<int> GLJ_TRAN_ID { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<gl_journal_items> gl_journal_items { get; set; }
    }
}
