//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItems
    {
        public MenuItems()
        {
            this.menu_permissions = new HashSet<menu_permissions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> Order { get; set; }
        public bool IsSeparator { get; set; }
        public string Command { get; set; }
        public string Module { get; set; }
        public string Icon { get; set; }
        public string MenuTag { get; set; }
        public Nullable<bool> RequiresEntity { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string Param3 { get; set; }
        public string Param4 { get; set; }
        public string Param5 { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> OnlyAdminUsers { get; set; }
        public string Group { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<menu_permissions> menu_permissions { get; set; }
    }
}
