//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class occupation_types
    {
        public occupation_types()
        {
            this.profile = new HashSet<profile>();
        }
    
        public int occtyp_id { get; set; }
        public string occtyp_created_who { get; set; }
        public System.DateTime occtyp_created_when { get; set; }
        public string occtyp_updated_who { get; set; }
        public Nullable<System.DateTime> occtyp_updated_when { get; set; }
        public string occtyp_name { get; set; }
        public string occtyp_desc { get; set; }
        public bool occtyp_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<profile> profile { get; set; }
    }
}
