//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile_status
    {
        public profile_status()
        {
            this.profile = new HashSet<profile>();
        }
    
        public int profstat_id { get; set; }
        public string profstat_created_who { get; set; }
        public System.DateTime profstat_created_when { get; set; }
        public string profstat_updated_who { get; set; }
        public Nullable<System.DateTime> profstat_updated_when { get; set; }
        public string profstat_name { get; set; }
        public string profstat_desc { get; set; }
        public bool profstat_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<profile> profile { get; set; }
    }
}
