//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sunrise_server_codes
    {
        public int sunserco_id { get; set; }
        public string sunserco_created_who { get; set; }
        public System.DateTime sunserco_created_when { get; set; }
        public string sunserco_updated_who { get; set; }
        public Nullable<System.DateTime> sunserco_updated_when { get; set; }
        public string sunserco_name { get; set; }
        public string sunserco_desc { get; set; }
        public bool sunserco_inactive { get; set; }
        public string sunserco_login { get; set; }
        public string sunserco_password { get; set; }
        public string sunserco_url { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
