//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_report_sunrise_import_policies
    {
        public int seq_no { get; set; }
        public string supplier_id { get; set; }
        public string supplier_policy_no { get; set; }
        public string version_no { get; set; }
        public string insured_name { get; set; }
        public string product_id { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string is_imported { get; set; }
        public string server { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
