//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_adjustments
    {
        public string accadj_username { get; set; }
        public double accadj_credit { get; set; }
        public Nullable<double> accadj_maximum_amount { get; set; }
        public Nullable<double> accadj_maximum_percentage { get; set; }
        public double accadj_allow_users_to_adjust { get; set; }
    }
}
