//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarm_types
    {
        public int alatyp_id { get; set; }
        public string alatyp_created_who { get; set; }
        public System.DateTime alatyp_created_when { get; set; }
        public string alatyp_updated_who { get; set; }
        public Nullable<System.DateTime> alatyp_updated_when { get; set; }
        public string alatyp_name { get; set; }
        public string alatyp_desc { get; set; }
        public Nullable<int> alatyp_sort { get; set; }
        public bool alatyp_inactive { get; set; }
    }
}
