//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class aqd_insurers
    {
        public int aqdins_id { get; set; }
        public string aqdins_name { get; set; }
        public string aqdins_ref_id { get; set; }
        public int aqdins_insurer { get; set; }
        public int aqdins_product_type { get; set; }
        public string aqdins_created_who { get; set; }
        public System.DateTime aqdins_created_when { get; set; }
        public string aqdins_updated_who { get; set; }
        public Nullable<System.DateTime> aqdins_updated_when { get; set; }
        public int aqdins_sort { get; set; }
        public bool aqdins_inactive { get; set; }
    }
}
