//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankReconciliations
    {
        public int bkrec_id { get; set; }
        public System.DateTime bkrec_date { get; set; }
        public decimal bkrec_amount { get; set; }
    }
}
