//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class brokerlink_conversions
    {
        public int brocon_id { get; set; }
        public string brocon_created_who { get; set; }
        public System.DateTime brocon_created_when { get; set; }
        public string brocon_updated_who { get; set; }
        public Nullable<System.DateTime> brocon_updated_when { get; set; }
        public string brocon_name { get; set; }
        public string brocon_desc { get; set; }
        public Nullable<int> brocon_sort { get; set; }
        public bool brocon_inactive { get; set; }
        public Nullable<int> brocon_ref_num { get; set; }
        public Nullable<int> brocon_conv_type { get; set; }
        public Nullable<int> brocon_bs_pol_key { get; set; }
        public string brocon_db_pol_key { get; set; }
    }
}
