//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class brokerlink_renewal_takeup
    {
        public int brorenta_id { get; set; }
        public string brorenta_created_who { get; set; }
        public System.DateTime brorenta_created_when { get; set; }
        public string brorenta_updated_who { get; set; }
        public Nullable<System.DateTime> brorenta_updated_when { get; set; }
        public string brorenta_name { get; set; }
        public string brorenta_desc { get; set; }
        public Nullable<int> brorenta_sort { get; set; }
        public bool brorenta_inactive { get; set; }
        public string brorenta_policy_number { get; set; }
        public Nullable<System.DateTime> brorenta_date_to { get; set; }
        public Nullable<int> brorenta_policy { get; set; }
        public string brorenta_rtkup_key { get; set; }
    
        public virtual policies policies { get; set; }
    }
}
