//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class building_types
    {
        public int buityp_id { get; set; }
        public string buityp_created_who { get; set; }
        public System.DateTime buityp_created_when { get; set; }
        public string buityp_updated_who { get; set; }
        public Nullable<System.DateTime> buityp_updated_when { get; set; }
        public string buityp_name { get; set; }
        public string buityp_desc { get; set; }
        public Nullable<int> buityp_sort { get; set; }
        public bool buityp_inactive { get; set; }
    }
}
