//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class building_ages
    {
        public int buiage_id { get; set; }
        public string buiage_created_who { get; set; }
        public System.DateTime buiage_created_when { get; set; }
        public string buiage_updated_who { get; set; }
        public Nullable<System.DateTime> buiage_updated_when { get; set; }
        public string buiage_name { get; set; }
        public string buiage_desc { get; set; }
        public Nullable<int> buiage_sort { get; set; }
        public bool buiage_inactive { get; set; }
    }
}
