//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessMachineryBreakdown
    {
        public int BusinessMachineryBreakdownId { get; set; }
        public int WorkbookId { get; set; }
        public string BlanketCover { get; set; }
        public Nullable<decimal> DeteriorationOfStock { get; set; }
        public string DeteriorationExcess { get; set; }
        public string Excess { get; set; }
        public int PremiumId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Endorsements { get; set; }
        public Nullable<bool> Validated { get; set; }
        public Nullable<int> NumUnits { get; set; }
    }
}
