//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessTheft
    {
        public int BusinessTheftId { get; set; }
        public int ParentId { get; set; }
        public Nullable<bool> Deadlocks { get; set; }
        public Nullable<bool> KeyLocks { get; set; }
        public string AlarmSystem { get; set; }
        public string SecurityPatrol { get; set; }
        public string OtherSecurityDesc { get; set; }
        public string OtherSecurity { get; set; }
        public Nullable<decimal> Contents { get; set; }
        public Nullable<decimal> Tobacco { get; set; }
        public Nullable<decimal> Alcohol { get; set; }
        public string OtherSIDesc1 { get; set; }
        public Nullable<decimal> OtherSI1 { get; set; }
        public string OtherSIDesc2 { get; set; }
        public Nullable<decimal> OtherSI2 { get; set; }
        public string Excess { get; set; }
        public Nullable<bool> EndorsementsApply { get; set; }
        public Nullable<int> PremiumId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Endorsements { get; set; }
        public Nullable<bool> Validated { get; set; }
    }
}
