//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessMoney
    {
        public int BusinessMoneyId { get; set; }
        public int ParentId { get; set; }
        public Nullable<decimal> MoneyInTransit { get; set; }
        public Nullable<decimal> MoneyInPrivate { get; set; }
        public Nullable<decimal> DuringBusHours { get; set; }
        public Nullable<decimal> OutsideBusHours { get; set; }
        public Nullable<decimal> InSafe { get; set; }
        public string Excess { get; set; }
        public int PremiumId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Endorsements { get; set; }
        public Nullable<bool> Validated { get; set; }
    }
}
