//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessTaxAudit
    {
        public int BusinessTaxAuditId { get; set; }
        public int WorkbookId { get; set; }
        public string TaxAudit { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> NumLocations { get; set; }
        public Nullable<decimal> AnnualTurnover { get; set; }
        public Nullable<bool> ATONotification { get; set; }
        public string Excess { get; set; }
        public Nullable<bool> EndorsementsApply { get; set; }
        public Nullable<int> PremiumId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Endorsements { get; set; }
        public Nullable<bool> Validated { get; set; }
    }
}
