//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_types
    {
        public category_types()
        {
            this.categories = new HashSet<categories>();
        }
    
        public int cattyp_id { get; set; }
        public string cattyp_created_who { get; set; }
        public System.DateTime cattyp_created_when { get; set; }
        public string cattyp_updated_who { get; set; }
        public Nullable<System.DateTime> cattyp_updated_when { get; set; }
        public string cattyp_name { get; set; }
        public string cattyp_desc { get; set; }
        public int cattyp_sort { get; set; }
        public bool cattyp_inactive { get; set; }
    
        public virtual ICollection<categories> categories { get; set; }
    }
}
