//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cause_codes
    {
        public int caucod_id { get; set; }
        public string caucod_created_who { get; set; }
        public System.DateTime caucod_created_when { get; set; }
        public string caucod_updated_who { get; set; }
        public Nullable<System.DateTime> caucod_updated_when { get; set; }
        public string caucod_name { get; set; }
        public string caucod_desc { get; set; }
        public Nullable<int> caucod_sort { get; set; }
        public bool caucod_inactive { get; set; }
    }
}
