//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class claims
    {
        public claims()
        {
            this.claim_tasks = new HashSet<claim_tasks>();
        }
    
        public int cla_id { get; set; }
        public int cla_parent_id { get; set; }
        public string cla_created_who { get; set; }
        public System.DateTime cla_created_when { get; set; }
        public string cla_updated_who { get; set; }
        public Nullable<System.DateTime> cla_updated_when { get; set; }
        public Nullable<int> cla_duration { get; set; }
        public bool cla_closed { get; set; }
        public Nullable<int> cla_status { get; set; }
        public Nullable<System.DateTime> cla_date_of_loss { get; set; }
        public Nullable<System.DateTime> cla_date_reported { get; set; }
        public string cla_insurer_reference { get; set; }
        public Nullable<decimal> cla_excess { get; set; }
        public Nullable<decimal> cla_estimate_of_loss { get; set; }
        public Nullable<decimal> cla_paid { get; set; }
        public string cla_subject_of_loss { get; set; }
        public string cla_result_of_loss { get; set; }
        public string cla_cause_of_loss { get; set; }
        public string cla_nature_of_loss { get; set; }
        public string cla_insurer_notes { get; set; }
        public Nullable<System.DateTime> cla_review_date { get; set; }
        public string cla_review_action { get; set; }
        public Nullable<int> cla_pol_id { get; set; }
        public Nullable<int> cla_subject { get; set; }
        public Nullable<int> cla_result { get; set; }
        public Nullable<int> cla_cause { get; set; }
        public string cla_brief_description { get; set; }
        public Nullable<int> cla_wor_id { get; set; }
        public Nullable<System.DateTime> cla_close_date { get; set; }
        public Nullable<System.DateTime> cla_reopen_date { get; set; }
        public string cla_sit_reg { get; set; }
        public string cla_insurer_contact { get; set; }
        public string cla_insurer_phone { get; set; }
        public string cla_insurer_email { get; set; }
        public string cla_assessor_contact { get; set; }
        public string cla_assessor_phone { get; set; }
        public string cla_assessor_email { get; set; }
        public Nullable<bool> cla_insurer_advised { get; set; }
        public Nullable<System.DateTime> cla_insurer_advised_date { get; set; }
        public Nullable<bool> cla_assessor_appro { get; set; }
        public Nullable<System.DateTime> cla_assessor_appro_date { get; set; }
        public Nullable<bool> cla_assessor_adv { get; set; }
        public Nullable<bool> cla_assessor_req { get; set; }
        public Nullable<int> CatastropheCode { get; set; }
        public Nullable<System.DateTime> cla_finalized { get; set; }
        public string cla_reopen_by { get; set; }
        public string cla_closed_by { get; set; }
        public Nullable<decimal> cla_pay_outstanding { get; set; }
        public string cla_location_desc { get; set; }
        public string cla_renter { get; set; }
        public string cla_location { get; set; }
        public string cla_location_state { get; set; }
        public string cla_location_postcode { get; set; }
        public string cla_driver { get; set; }
        public string cla_driver_age { get; set; }
        public string cla_licence_no { get; set; }
        public string cla_vehicle_desc1 { get; set; }
        public Nullable<int> cla_vehicle_desc2 { get; set; }
        public string cla_tp_driver { get; set; }
        public string cla_tp_rego_no { get; set; }
        public string cla_tp_driver_age { get; set; }
        public string cla_tp_licence_no { get; set; }
        public string cla_tp_reg_owner { get; set; }
        public string cla_tp_make { get; set; }
        public string cla_tp_model { get; set; }
        public string cla_tp_insurer { get; set; }
        public string cla_tp_address_1 { get; set; }
        public string cla_tp_address_2 { get; set; }
        public string cla_tp_address_3 { get; set; }
        public string cla_tp_address_state { get; set; }
        public string cla_tp_address_postcode { get; set; }
        public string cla_tp_insurer_clm_no { get; set; }
        public string cla_tp_phone_no { get; set; }
        public string cla_tp_insurer_phone_no { get; set; }
        public Nullable<int> cla_cause_code { get; set; }
        public Nullable<int> cla_liability_code { get; set; }
        public string cla_tp_assessor { get; set; }
        public string cla_tp_solicitor { get; set; }
    
        public virtual Claim_Catastrophe_Code Claim_Catastrophe_Code { get; set; }
        public virtual claim_causes claim_causes { get; set; }
        public virtual claim_results claim_results { get; set; }
        public virtual claim_status_types claim_status_types { get; set; }
        public virtual claim_subjects claim_subjects { get; set; }
        public virtual ICollection<claim_tasks> claim_tasks { get; set; }
        public virtual claim_workbooks claim_workbooks { get; set; }
        public virtual general_insurance general_insurance { get; set; }
        public virtual policies policies { get; set; }
    }
}
