//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimPayments
    {
        public int clapay_id { get; set; }
        public int clapay_claimid { get; set; }
        public System.DateTime clapay_date { get; set; }
        public int clapay_type { get; set; }
        public int clapay_details { get; set; }
        public decimal clapay_excess { get; set; }
        public decimal clapay_movement { get; set; }
        public decimal clapay_gst { get; set; }
        public string clapay_cheqno { get; set; }
        public string clapay_payee { get; set; }
        public int clapay_section { get; set; }
    }
}
