//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClausesSections
    {
        public int cla_sec_id { get; set; }
        public string cla_sec_Cob_name { get; set; }
        public string cla_sec_section_name { get; set; }
        public Nullable<bool> cla_sec_inactive { get; set; }
    }
}
