//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Notes
    {
        public string ent_name { get; set; }
        public string ent_address_1 { get; set; }
        public string ent_address_2 { get; set; }
        public string ent_address_3 { get; set; }
        public string ent_suburb { get; set; }
        public string ent_postcode { get; set; }
        public string not_Contact { get; set; }
        public string not_Subject { get; set; }
        public System.DateTime not_created_when { get; set; }
        public string not_created_who { get; set; }
        public string not_note { get; set; }
        public int not_id { get; set; }
        public string Doc { get; set; }
        public string State { get; set; }
        public int spid { get; set; }
    }
}
