//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Task_Notes
    {
        public int Client_not_id { get; set; }
        public int Client_not_parent_id { get; set; }
        public string Client_not_created_who { get; set; }
        public System.DateTime Client_not_created_when { get; set; }
        public string Client_not_updated_who { get; set; }
        public Nullable<System.DateTime> Client_not_updated_when { get; set; }
        public string Client_not_note { get; set; }
        public string Client_not_Contact { get; set; }
        public string Client_not_Subject { get; set; }
        public string Client_not_phone { get; set; }
        public string Client_not_mobile { get; set; }
        public string Client_not_email { get; set; }
    
        public virtual tasks tasks { get; set; }
    }
}
