//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetails_Category3
    {
        public ClientDetails_Category3()
        {
            this.entities = new HashSet<entities>();
        }
    
        public int cdcat3_id { get; set; }
        public string cdcat3_created_who { get; set; }
        public System.DateTime cdcat3_created_when { get; set; }
        public string cdcat3_updated_who { get; set; }
        public Nullable<System.DateTime> cdcat3_updated_when { get; set; }
        public string cdcat3_name { get; set; }
        public string cdcat3_desc { get; set; }
        public int cdcat3_sort { get; set; }
        public bool cdcat3_inactive { get; set; }
    
        public virtual ICollection<entities> entities { get; set; }
    }
}
