//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class compensation_types
    {
        public int comtyp_id { get; set; }
        public string comtyp_created_who { get; set; }
        public System.DateTime comtyp_created_when { get; set; }
        public string comtyp_updated_who { get; set; }
        public Nullable<System.DateTime> comtyp_updated_when { get; set; }
        public string comtyp_name { get; set; }
        public string comtyp_desc { get; set; }
        public Nullable<int> comtyp_sort { get; set; }
        public bool comtyp_inactive { get; set; }
    }
}
