//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomRowTableItems
    {
        public CustomRowTableItems()
        {
            this.CustomRowDropDownListItems = new HashSet<CustomRowDropDownListItems>();
            this.CustomRowSumTextBoxItems = new HashSet<CustomRowSumTextBoxItems>();
        }
    
        public int Id { get; set; }
        public int CustomTableItemId { get; set; }
        public string CustomRowItemType { get; set; }
        public string FieldName { get; set; }
        public string DefaultText { get; set; }
        public string TextAlignment { get; set; }
        public Nullable<bool> Multiline { get; set; }
        public Nullable<int> Width { get; set; }
        public string DescriptionText { get; set; }
        public Nullable<decimal> DefaultValue { get; set; }
        public Nullable<decimal> MinimumValue { get; set; }
        public Nullable<decimal> MaximumValue { get; set; }
        public Nullable<bool> DisplayCents { get; set; }
        public Nullable<bool> ShowCommas { get; set; }
        public Nullable<int> DecimalPlaces { get; set; }
        public Nullable<System.DateTime> DefaultDate { get; set; }
        public Nullable<System.DateTime> MinimumDate { get; set; }
        public Nullable<System.DateTime> MaximumDate { get; set; }
        public string DefaultSelectedItem { get; set; }
        public string ToolTipText { get; set; }
        public Nullable<int> Height { get; set; }
        public string XPath { get; set; }
        public Nullable<int> CustomRowItemPosition { get; set; }
        public Nullable<bool> ShowSum { get; set; }
        public string SumLabel { get; set; }
        public string PrefixText { get; set; }
        public string SuffixText { get; set; }
        public Nullable<int> attab_id { get; set; }
        public Nullable<int> TabIndex { get; set; }
        public string AturaTag { get; set; }
    
        public virtual atura_tables atura_tables { get; set; }
        public virtual ICollection<CustomRowDropDownListItems> CustomRowDropDownListItems { get; set; }
        public virtual ICollection<CustomRowSumTextBoxItems> CustomRowSumTextBoxItems { get; set; }
        public virtual CustomTableItems CustomTableItems { get; set; }
    }
}
