//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomDropDownListTableItems
    {
        public CustomDropDownListTableItems()
        {
            this.CustomDropDownListTableItemsItems = new HashSet<CustomDropDownListTableItemsItems>();
        }
    
        public int Id { get; set; }
        public int CustomTableItemId { get; set; }
        public string SelectedItem { get; set; }
        public Nullable<int> attab_id { get; set; }
    
        public virtual atura_tables atura_tables { get; set; }
        public virtual CustomTableItems CustomTableItems { get; set; }
        public virtual ICollection<CustomDropDownListTableItemsItems> CustomDropDownListTableItemsItems { get; set; }
    }
}
