//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomRowDropDownListItems
    {
        public int Id { get; set; }
        public int CustomRowTableItemId { get; set; }
        public string Item { get; set; }
        public int Position { get; set; }
    
        public virtual CustomRowTableItems CustomRowTableItems { get; set; }
    }
}
