//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentRepository
    {
        public int dr_id { get; set; }
        public string dr_name { get; set; }
        public string dr_description { get; set; }
        public byte[] dr_document { get; set; }
        public string dr_filename { get; set; }
        public string dr_created_who { get; set; }
        public Nullable<System.DateTime> dr_created_when { get; set; }
        public string dr_updated_who { get; set; }
        public Nullable<System.DateTime> dr_updated_when { get; set; }
        public bool dr_inactive { get; set; }
        public Nullable<int> dr_insurer { get; set; }
        public Nullable<int> dr_cob { get; set; }
        public int dr_sharing { get; set; }
        public Nullable<int> dr_branch { get; set; }
    }
}
