//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int DriverId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<int> YearLicenced { get; set; }
        public Nullable<bool> Accidents { get; set; }
        public string AccidentsText { get; set; }
        public Nullable<bool> Convictions { get; set; }
        public string ConvictionsText { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public string CancelledText { get; set; }
        public Nullable<bool> Refused { get; set; }
        public string RefusedText { get; set; }
        public Nullable<bool> Claims { get; set; }
        public string ClaimsText { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    }
}
