//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class farm_excesses
    {
        public int farexc_id { get; set; }
        public string farexc_created_who { get; set; }
        public System.DateTime farexc_created_when { get; set; }
        public string farexc_updated_who { get; set; }
        public Nullable<System.DateTime> farexc_updated_when { get; set; }
        public string farexc_name { get; set; }
        public string farexc_desc { get; set; }
        public Nullable<int> farexc_sort { get; set; }
        public bool farexc_inactive { get; set; }
        public Nullable<int> farexc_product { get; set; }
        public Nullable<decimal> farexc_discount { get; set; }
    
        public virtual risk_sections risk_sections { get; set; }
    }
}
