//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class floor_types
    {
        public int flotyp_id { get; set; }
        public string flotyp_created_who { get; set; }
        public System.DateTime flotyp_created_when { get; set; }
        public string flotyp_updated_who { get; set; }
        public Nullable<System.DateTime> flotyp_updated_when { get; set; }
        public string flotyp_name { get; set; }
        public string flotyp_desc { get; set; }
        public Nullable<int> flotyp_sort { get; set; }
        public bool flotyp_inactive { get; set; }
    }
}
