//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class garaged_types
    {
        public int gartyp_id { get; set; }
        public string gartyp_created_who { get; set; }
        public System.DateTime gartyp_created_when { get; set; }
        public string gartyp_updated_who { get; set; }
        public Nullable<System.DateTime> gartyp_updated_when { get; set; }
        public string gartyp_name { get; set; }
        public string gartyp_desc { get; set; }
        public Nullable<int> gartyp_sort { get; set; }
        public bool gartyp_inactive { get; set; }
    }
}
