//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class geographical_limits
    {
        public int geolim_id { get; set; }
        public string geolim_created_who { get; set; }
        public System.DateTime geolim_created_when { get; set; }
        public string geolim_updated_who { get; set; }
        public Nullable<System.DateTime> geolim_updated_when { get; set; }
        public string geolim_name { get; set; }
        public string geolim_desc { get; set; }
        public Nullable<int> geolim_sort { get; set; }
        public bool geolim_inactive { get; set; }
    }
}
