//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_sl_entities
    {
        public gl_sl_entities()
        {
            this.gl_rules = new HashSet<gl_rules>();
        }
    
        public string gle_name { get; set; }
        public string gle_move_ref_view { get; set; }
        public string gle_move_ref_column { get; set; }
        public string gle_sub_ledger_name { get; set; }
        public string gle_created_who { get; set; }
        public System.DateTime gle_created_when { get; set; }
        public string gle_updated_who { get; set; }
        public Nullable<System.DateTime> gle_updated_when { get; set; }
    
        public virtual ICollection<gl_rules> gl_rules { get; set; }
    }
}
