//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePolicy
    {
        public int HomePolicyId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public decimal UnderwriterFee { get; set; }
        public decimal UnderwriterFeeGST { get; set; }
        public string DefaultExcess { get; set; }
        public Nullable<bool> IsfullTermPolicy { get; set; }
    
        public virtual workbooks workbooks { get; set; }
    }
}
