//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibs_policy_text
    {
        public int ibspolte_id { get; set; }
        public int ibspolte_parent_id { get; set; }
        public string ibspolte_created_who { get; set; }
        public System.DateTime ibspolte_created_when { get; set; }
        public string ibspolte_updated_who { get; set; }
        public Nullable<System.DateTime> ibspolte_updated_when { get; set; }
        public Nullable<int> ibspolte_duration { get; set; }
        public string ibspolte_text { get; set; }
    
        public virtual ibs_policies ibs_policies { get; set; }
    }
}
