//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurer_masterlist
    {
        public string ent_name { get; set; }
        public string ent_address_1 { get; set; }
        public string ent_address_2 { get; set; }
        public string ent_address_3 { get; set; }
        public string ent_suburb { get; set; }
        public Nullable<int> ent_state { get; set; }
        public string sta_name { get; set; }
        public string ent_postcode { get; set; }
        public string ent_contact { get; set; }
        public string ent_telephone { get; set; }
        public Nullable<short> cob_days_credit { get; set; }
        public Nullable<short> cob_days_held_covered { get; set; }
        public Nullable<decimal> cob_commission { get; set; }
        public string gencob_name { get; set; }
        public Nullable<decimal> pol_sum_insured_MTD { get; set; }
        public Nullable<decimal> pol_total_base_premium_MTD { get; set; }
        public Nullable<decimal> pol_total_levies_MTD { get; set; }
        public Nullable<decimal> pol_total_duties_MTD { get; set; }
        public Nullable<decimal> pol_total_fees_MTD { get; set; }
        public Nullable<decimal> pol_total_gross_premium_MTD { get; set; }
        public Nullable<decimal> pol_total_commission_MTD { get; set; }
        public Nullable<decimal> pol_commission_MTD { get; set; }
        public Nullable<decimal> pol_commission_gst_MTD { get; set; }
        public Nullable<decimal> pol_insurer_gst_MTD { get; set; }
        public Nullable<decimal> pol_uw_fee_MTD { get; set; }
        public Nullable<decimal> pol_uw_fee_gst_MTD { get; set; }
        public Nullable<decimal> pol_othercharges_MTD { get; set; }
        public Nullable<decimal> pol_sub_agent_commission_MTD { get; set; }
        public Nullable<decimal> pol_total_net_premium_MTD { get; set; }
        public Nullable<decimal> pol_sum_insured { get; set; }
        public Nullable<decimal> pol_total_base_premium { get; set; }
        public Nullable<decimal> pol_total_levies { get; set; }
        public Nullable<decimal> pol_total_duties { get; set; }
        public Nullable<decimal> pol_total_fees { get; set; }
        public Nullable<decimal> pol_total_gross_premium { get; set; }
        public Nullable<decimal> pol_total_commission { get; set; }
        public Nullable<decimal> pol_commission { get; set; }
        public Nullable<decimal> pol_commission_gst { get; set; }
        public Nullable<decimal> pol_insurer_gst { get; set; }
        public Nullable<decimal> pol_uw_fee { get; set; }
        public Nullable<decimal> pol_uw_fee_gst { get; set; }
        public Nullable<decimal> pol_othercharges { get; set; }
        public Nullable<decimal> pol_sub_agent_commission { get; set; }
        public Nullable<decimal> pol_total_net_premium { get; set; }
        public Nullable<decimal> cla_paid_MTD { get; set; }
        public Nullable<decimal> cla_paid { get; set; }
        public int insurer_id { get; set; }
        public Nullable<int> gencob_id { get; set; }
        public short SPID { get; set; }
    }
}
