//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class liability_limits
    {
        public int lialim_id { get; set; }
        public string lialim_created_who { get; set; }
        public System.DateTime lialim_created_when { get; set; }
        public string lialim_updated_who { get; set; }
        public Nullable<System.DateTime> lialim_updated_when { get; set; }
        public string lialim_name { get; set; }
        public string lialim_desc { get; set; }
        public Nullable<int> lialim_sort { get; set; }
        public bool lialim_inactive { get; set; }
    }
}
