//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthly_policies
    {
        public int mp_id { get; set; }
        public string mp_scheme { get; set; }
        public Nullable<int> mp_insurer_id { get; set; }
        public Nullable<int> mp_gencob_id { get; set; }
        public int mp_frequency { get; set; }
        public int mp_no_payments { get; set; }
        public int mp_no_deposit { get; set; }
        public bool mp_spread_rp { get; set; }
        public bool mp_spread_ap { get; set; }
        public string mp_created_who { get; set; }
        public System.DateTime mp_created_when { get; set; }
        public string mp_updated_who { get; set; }
        public System.DateTime mp_updated_when { get; set; }
        public Nullable<bool> mp_bf_inc_deposit { get; set; }
    }
}
