//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mv_body_types
    {
        public int mvbodtyp_id { get; set; }
        public string mvbodtyp_created_who { get; set; }
        public System.DateTime mvbodtyp_created_when { get; set; }
        public string mvbodtyp_updated_who { get; set; }
        public Nullable<System.DateTime> mvbodtyp_updated_when { get; set; }
        public string mvbodtyp_name { get; set; }
        public string mvbodtyp_desc { get; set; }
        public Nullable<int> mvbodtyp_sort { get; set; }
        public bool mvbodtyp_inactive { get; set; }
    }
}
