//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlinePaymentItems
    {
        public int OnlinePayment_id { get; set; }
        public int OnlinePayment_ent_id { get; set; }
        public Nullable<int> OnlinePayment_pol_tran_id { get; set; }
        public string OnlinePayment_policy_number { get; set; }
        public Nullable<int> OnlinePayment_pol_id { get; set; }
        public int OnlinePayment_status { get; set; }
        public System.DateTime OnlinePayment_timestamp { get; set; }
    }
}
