//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class organisation_structures
    {
        public organisation_structures()
        {
            this.profile = new HashSet<profile>();
            this.WorkbookMappings_Client = new HashSet<WorkbookMappings_Client>();
            this.profile1 = new HashSet<profile>();
        }
    
        public int orgstr_id { get; set; }
        public string orgstr_created_who { get; set; }
        public System.DateTime orgstr_created_when { get; set; }
        public string orgstr_updated_who { get; set; }
        public Nullable<System.DateTime> orgstr_updated_when { get; set; }
        public string orgstr_name { get; set; }
        public string orgstr_desc { get; set; }
        public int orgstr_sort { get; set; }
        public bool orgstr_inactive { get; set; }
    
        public virtual ICollection<profile> profile { get; set; }
        public virtual ICollection<WorkbookMappings_Client> WorkbookMappings_Client { get; set; }
        public virtual ICollection<profile> profile1 { get; set; }
    }
}
