//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_methods
    {
        public int paymet_id { get; set; }
        public string paymet_method { get; set; }
        public Nullable<int> paymet_banking_section { get; set; }
    }
}
