//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class periods
    {
        public int prd_id { get; set; }
        public string prd_created_who { get; set; }
        public System.DateTime prd_created_when { get; set; }
        public string prd_updated_who { get; set; }
        public Nullable<System.DateTime> prd_updated_when { get; set; }
        public string prd_name { get; set; }
        public string prd_desc { get; set; }
        public Nullable<int> prd_sort { get; set; }
        public bool prd_inactive { get; set; }
    }
}
