//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_types
    {
        public personnel_types()
        {
            this.personnel = new HashSet<personnel>();
        }
    
        public int pertyp_id { get; set; }
        public string pertyp_created_who { get; set; }
        public System.DateTime pertyp_created_when { get; set; }
        public string pertyp_updated_who { get; set; }
        public Nullable<System.DateTime> pertyp_updated_when { get; set; }
        public string pertyp_name { get; set; }
        public string pertyp_desc { get; set; }
        public int pertyp_sort { get; set; }
        public bool pertyp_inactive { get; set; }
    
        public virtual ICollection<personnel> personnel { get; set; }
    }
}
