//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class pha_products
    {
        public pha_products()
        {
            this.general_insurance = new HashSet<general_insurance>();
            this.sunrise_products = new HashSet<sunrise_products>();
        }
    
        public int phapro_id { get; set; }
        public string phapro_created_who { get; set; }
        public System.DateTime phapro_created_when { get; set; }
        public string phapro_updated_who { get; set; }
        public Nullable<System.DateTime> phapro_updated_when { get; set; }
        public string phapro_name { get; set; }
        public string phapro_desc { get; set; }
        public Nullable<int> phapro_sort { get; set; }
        public bool phapro_inactive { get; set; }
        public Nullable<int> phapro_rating { get; set; }
        public string phapro_comments { get; set; }
        public Nullable<int> phapro_class_of_business { get; set; }
        public Nullable<int> phapro_insurer { get; set; }
    
        public virtual entities entities { get; set; }
        public virtual gen_ins_classes_of_business gen_ins_classes_of_business { get; set; }
        public virtual ICollection<general_insurance> general_insurance { get; set; }
        public virtual pha_ratings pha_ratings { get; set; }
        public virtual ICollection<sunrise_products> sunrise_products { get; set; }
    }
}
