//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class policy_subsections
    {
        public int polss_pol_id { get; set; }
        public string polss_name { get; set; }
        public Nullable<decimal> polss_premium_base { get; set; }
        public Nullable<decimal> polss_tl { get; set; }
        public Nullable<decimal> polss_fsl { get; set; }
        public Nullable<decimal> polss_premium_gst { get; set; }
        public Nullable<decimal> polss_sd { get; set; }
        public Nullable<decimal> polss_comm { get; set; }
        public Nullable<decimal> polss_comm_gst { get; set; }
        public Nullable<decimal> polss_excess { get; set; }
        public string polss_postcode { get; set; }
        public string polss_state { get; set; }
    }
}
