//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliciesNotPosted
    {
        public string ent_name { get; set; }
        public string genins_name { get; set; }
        public string gentrans_name { get; set; }
        public string saltea_name { get; set; }
        public string pol_invoice_total { get; set; }
        public string pol_base_premium { get; set; }
        public System.DateTime wor_created_when { get; set; }
        public Nullable<System.DateTime> pol_date_from { get; set; }
        public Nullable<System.DateTime> pol_date_to { get; set; }
        public string Insurer { get; set; }
        public string pol_policy_number { get; set; }
        public string tran_type { get; set; }
        public short spid { get; set; }
        public int wor_id { get; set; }
        public Nullable<int> saletea_id { get; set; }
    }
}
