//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premiums
    {
        public Premiums()
        {
            this.FarmInterruption = new HashSet<FarmInterruption>();
            this.FarmLiability = new HashSet<FarmLiability>();
            this.FarmProperty = new HashSet<FarmProperty>();
            this.FarmProperty1 = new HashSet<FarmProperty>();
            this.GeneralProperty = new HashSet<GeneralProperty>();
            this.Home = new HashSet<Home>();
            this.LandTransit = new HashSet<LandTransit>();
            this.MachineryBreakdown = new HashSet<MachineryBreakdown>();
            this.Motor = new HashSet<Motor>();
            this.PersonalAccident = new HashSet<PersonalAccident>();
            this.VehicleMachinery = new HashSet<VehicleMachinery>();
        }
    
        public int PremiumId { get; set; }
        public int ParentId { get; set; }
        public Nullable<decimal> BasePremium { get; set; }
        public Nullable<decimal> FSL { get; set; }
        public Nullable<decimal> FSLPerc { get; set; }
        public Nullable<decimal> PremiumGST { get; set; }
        public Nullable<decimal> StampDuty { get; set; }
        public Nullable<decimal> StampDutyPerc { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> CommissionPerc { get; set; }
        public Nullable<decimal> CommissionGST { get; set; }
        public Nullable<decimal> TerrorismLevy { get; set; }
        public Nullable<decimal> SumInsured { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<decimal> TerrorismLevyPerc { get; set; }
        public Nullable<decimal> PremiumGSTPerc { get; set; }
        public Nullable<decimal> CommissionGSTPerc { get; set; }
        public Nullable<decimal> FutureBasePremium { get; set; }
        public Nullable<decimal> TotalInsuredBefore { get; set; }
        public Nullable<decimal> BaseRateBefore { get; set; }
        public Nullable<decimal> BasePremiumBefore { get; set; }
    
        public virtual ICollection<FarmInterruption> FarmInterruption { get; set; }
        public virtual ICollection<FarmLiability> FarmLiability { get; set; }
        public virtual ICollection<FarmProperty> FarmProperty { get; set; }
        public virtual ICollection<FarmProperty> FarmProperty1 { get; set; }
        public virtual ICollection<GeneralProperty> GeneralProperty { get; set; }
        public virtual ICollection<Home> Home { get; set; }
        public virtual ICollection<LandTransit> LandTransit { get; set; }
        public virtual ICollection<MachineryBreakdown> MachineryBreakdown { get; set; }
        public virtual ICollection<Motor> Motor { get; set; }
        public virtual ICollection<PersonalAccident> PersonalAccident { get; set; }
        public virtual workbooks workbooks { get; set; }
        public virtual ICollection<VehicleMachinery> VehicleMachinery { get; set; }
    }
}
