//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_types
    {
        public int purtyp_id { get; set; }
        public string purtyp_created_who { get; set; }
        public System.DateTime purtyp_created_when { get; set; }
        public string purtyp_updated_who { get; set; }
        public Nullable<System.DateTime> purtyp_updated_when { get; set; }
        public string purtyp_name { get; set; }
        public string purtyp_desc { get; set; }
        public Nullable<int> purtyp_sort { get; set; }
        public bool purtyp_inactive { get; set; }
    }
}
