//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class rb_group
    {
        public rb_group()
        {
            this.rb_group_reports = new HashSet<rb_group_reports>();
        }
    
        public int rbg_id { get; set; }
        public Nullable<int> rbg_parent_id { get; set; }
        public string rbg_name { get; set; }
    
        public virtual ICollection<rb_group_reports> rb_group_reports { get; set; }
    }
}
