//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportQueries
    {
        public int ReportID { get; set; }
        public string ReportName { get; set; }
        public string ShowQuery { get; set; }
        public string ExecQuery { get; set; }
        public string ReportTitle { get; set; }
        public string DispRepFields { get; set; }
        public string DispRepFieldsSQL { get; set; }
        public string ReportHeader { get; set; }
        public string ReportFlds { get; set; }
        public string rptTotalFlds { get; set; }
        public string RptTotHeader { get; set; }
    }
}
