//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class required_wordings
    {
        public int reqwor_id { get; set; }
        public string reqwor_created_who { get; set; }
        public System.DateTime reqwor_created_when { get; set; }
        public string reqwor_updated_who { get; set; }
        public Nullable<System.DateTime> reqwor_updated_when { get; set; }
        public string reqwor_name { get; set; }
        public string reqwor_desc { get; set; }
        public Nullable<int> reqwor_sort { get; set; }
        public bool reqwor_inactive { get; set; }
    }
}
