//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residential
    {
        public Residential()
        {
            this.ResidentialSpecifiedContents = new HashSet<ResidentialSpecifiedContents>();
            this.ResidentialValuables = new HashSet<ResidentialValuables>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Roof { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public string BuildingType { get; set; }
        public string HolidayHouse { get; set; }
        public string Construction { get; set; }
        public string DoorSecurity { get; set; }
        public string BuildingConstruction { get; set; }
        public string Floors { get; set; }
        public string BuildingSize { get; set; }
        public string HowOccupied { get; set; }
        public string WindowSecurity { get; set; }
        public string Alarm { get; set; }
        public string FurtherDetails { get; set; }
        public Nullable<bool> UnoccupiedMoreThan60Days { get; set; }
        public Nullable<bool> HeritageListed { get; set; }
        public string PreviousInsurer { get; set; }
        public Nullable<decimal> SumInsuredBuilding { get; set; }
        public Nullable<decimal> SumInsuredUnspecifiedContents { get; set; }
        public Nullable<decimal> PubLiability { get; set; }
        public string Excess { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string OccupancyType { get; set; }
        public Nullable<bool> SomeoneAlwaysHome { get; set; }
        public Nullable<bool> WindowsStandardLocks { get; set; }
        public Nullable<bool> WindowsKeyLocks { get; set; }
        public Nullable<bool> WindowsSecurityScreens { get; set; }
        public Nullable<bool> WindowsLouvre { get; set; }
        public Nullable<bool> DoorsStandardLocks { get; set; }
        public Nullable<bool> DoorsSingleKey { get; set; }
        public Nullable<bool> DoorsDoubleKey { get; set; }
        public Nullable<bool> DoorsSliding { get; set; }
        public Nullable<bool> AlarmAudible { get; set; }
        public Nullable<bool> AlarmMonitored { get; set; }
        public Nullable<bool> SafeInstalled { get; set; }
        public Nullable<bool> InNeighbourhoodWatchArea { get; set; }
        public Nullable<int> NCBBaseYear { get; set; }
        public Nullable<System.DateTime> InsuredDOB { get; set; }
        public Nullable<bool> ConvertedToNewFormat { get; set; }
        public string Endorsements { get; set; }
        public Nullable<bool> Validated { get; set; }
        public string PolicyType { get; set; }
        public Nullable<int> PremiumBuildingId { get; set; }
        public Nullable<int> PremiumContentsId { get; set; }
        public Nullable<int> PremiumSpecifiedValuablesId { get; set; }
        public Nullable<decimal> LandlordWeeklyRent { get; set; }
        public Nullable<decimal> LandlordLossOfRent { get; set; }
        public Nullable<decimal> LandlordRentDefault { get; set; }
        public Nullable<decimal> LandlordStrataLossOfRent { get; set; }
        public Nullable<decimal> LandlordLegalExpenses { get; set; }
        public Nullable<bool> LandlordStrataTitle { get; set; }
        public string Security { get; set; }
    
        public virtual HomeLocation HomeLocation { get; set; }
        public virtual ICollection<ResidentialSpecifiedContents> ResidentialSpecifiedContents { get; set; }
        public virtual ICollection<ResidentialValuables> ResidentialValuables { get; set; }
    }
}
