//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sched_doc_queries
    {
        public sched_doc_queries()
        {
            this.sched_doc_prod = new HashSet<sched_doc_prod>();
        }
    
        public int schedque_id { get; set; }
        public string schedque_created_who { get; set; }
        public System.DateTime schedque_created_when { get; set; }
        public string schedque_updated_who { get; set; }
        public Nullable<System.DateTime> schedque_updated_when { get; set; }
        public string schedque_name { get; set; }
        public string schedque_desc { get; set; }
        public Nullable<int> schedque_sort { get; set; }
        public bool schedque_inactive { get; set; }
        public string schedque_query { get; set; }
    
        public virtual ICollection<sched_doc_prod> sched_doc_prod { get; set; }
    }
}
