//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class soa_clauses
    {
        public int cob_id { get; set; }
        public string nature_of_advice { get; set; }
        public string recommendations { get; set; }
        public string optional_notice1 { get; set; }
        public string optional_notice2 { get; set; }
        public string optional_notice3 { get; set; }
        public int soa_clauses_id { get; set; }
    }
}
