//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasks
    {
        public tasks()
        {
            this.Client_Task_Notes = new HashSet<Client_Task_Notes>();
            this.tasks_sub_tasks = new HashSet<tasks_sub_tasks>();
        }
    
        public int tas_id { get; set; }
        public int tas_parent_id { get; set; }
        public string tas_created_who { get; set; }
        public System.DateTime tas_created_when { get; set; }
        public string tas_updated_who { get; set; }
        public Nullable<System.DateTime> tas_updated_when { get; set; }
        public Nullable<int> tas_duration { get; set; }
        public bool tas_closed { get; set; }
        public string tas_initiated_by { get; set; }
        public string tas_contact_person { get; set; }
        public Nullable<int> tas_contact_method { get; set; }
        public string tas_brief_description { get; set; }
        public Nullable<int> tas_priority { get; set; }
        public Nullable<System.DateTime> tas_followup_date { get; set; }
        public string tas_followup_action { get; set; }
        public Nullable<int> tas_time_spent { get; set; }
        public Nullable<int> tas_status { get; set; }
        public string tas_notes { get; set; }
        public Nullable<int> tas_document_type { get; set; }
        public byte[] tas_document { get; set; }
        public Nullable<System.DateTime> tas_date { get; set; }
        public Nullable<int> tas_type { get; set; }
        public string tas_queue { get; set; }
        public string tas_hyperlink { get; set; }
        public Nullable<System.DateTime> tas_re_open_Date { get; set; }
        public string tas_re_open_User { get; set; }
        public string tas_original_que_person { get; set; }
        public string Fname { get; set; }
        public string tas_document_size { get; set; }
        public Nullable<bool> IsNewTask { get; set; }
        public string tas_contact_phone { get; set; }
        public string tas_contact_mobile { get; set; }
        public string tas_contact_email { get; set; }
    
        public virtual ICollection<Client_Task_Notes> Client_Task_Notes { get; set; }
        public virtual contact_methods contact_methods { get; set; }
        public virtual entities entities { get; set; }
        public virtual priorities priorities { get; set; }
        public virtual task_documents task_documents { get; set; }
        public virtual task_status_types task_status_types { get; set; }
        public virtual task_types task_types { get; set; }
        public virtual ICollection<tasks_sub_tasks> tasks_sub_tasks { get; set; }
    }
}
