//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCriteria
    {
        public int Rpt_Id { get; set; }
        public int Crit_Id { get; set; }
        public string Crit_FieldId { get; set; }
        public string Crit_FieldName { get; set; }
        public string Crit_FieldSource { get; set; }
        public Nullable<int> Crit_CondId { get; set; }
        public string Crit_CondName { get; set; }
        public string Crit_Type { get; set; }
        public short Crit_Visible { get; set; }
        public string Crit_Value { get; set; }
        public Nullable<int> Crit_ValueRole { get; set; }
    
        public virtual tblReport tblReport { get; set; }
    }
}
