//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblField
    {
        public int Rpt_Id { get; set; }
        public int Fld_Id { get; set; }
        public string Fld_Source { get; set; }
        public string Fld_Name { get; set; }
        public string Fld_Type { get; set; }
        public short Fld_SelectFlag { get; set; }
        public Nullable<short> Fld_SelectSeq { get; set; }
        public short Fld_SelectMandatory { get; set; }
        public short Fld_DisplayFlag { get; set; }
        public Nullable<short> Fld_DisplaySeq { get; set; }
        public Nullable<short> Fld_DisplaySize { get; set; }
        public short Fld_SortFlag { get; set; }
        public Nullable<short> Fld_SortSeq { get; set; }
        public short Fld_GroupFlag { get; set; }
        public short Fld_TotalFlag { get; set; }
    
        public virtual tblReport tblReport { get; set; }
        public virtual tblWork tblWork { get; set; }
    }
}
