//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public tblReport()
        {
            this.tblCriteria = new HashSet<tblCriteria>();
            this.tblField = new HashSet<tblField>();
        }
    
        public int Rpt_Id { get; set; }
        public string Rpt_Title { get; set; }
        public Nullable<int> Tbl_Id { get; set; }
        public short Rpt_OneAll { get; set; }
        public Nullable<System.DateTime> Rpt_DateUpdated { get; set; }
        public Nullable<System.DateTime> Rpt_DateCreated { get; set; }
    
        public virtual ICollection<tblCriteria> tblCriteria { get; set; }
        public virtual ICollection<tblField> tblField { get; set; }
    }
}
