//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_atura_tagrangevalue
    {
        public int attrv_attv_id { get; set; }
        public int attrv_row_id { get; set; }
        public int attrv_col_id { get; set; }
        public int attrv_index { get; set; }
        public string attrv_value { get; set; }
        public string guid { get; set; }
    }
}
