//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_claim
    {
        public string clmtmp_key { get; set; }
        public string clmtmp_client_code { get; set; }
        public string clmtmp_class_code { get; set; }
        public string clmtmp_claim_number { get; set; }
        public string clmtmp_status { get; set; }
        public string clmtmp_underwriter_reference { get; set; }
        public string clmtmp_claim_detail_line_1 { get; set; }
        public string clmtmp_claim_detail_line_2 { get; set; }
        public string clmtmp_claim_detail_line_3 { get; set; }
        public string clmtmp_claim_detail_line_4 { get; set; }
        public string clmtmp_memo_line_1 { get; set; }
        public string clmtmp_memo_line_2 { get; set; }
        public string clmtmp_memo_line_3 { get; set; }
        public string clmtmp_memo_line_4 { get; set; }
        public string clmtmp_action_line_1 { get; set; }
        public string clmtmp_action_line_2 { get; set; }
        public string clmtmp_sum_insured { get; set; }
        public string clmtmp_excess { get; set; }
        public string clmtmp_estimate { get; set; }
        public string clmtmp_paid { get; set; }
        public string clmtmp_date_of_loss { get; set; }
        public string clmtmp_review_date { get; set; }
        public string clmtmp_previous_review_date { get; set; }
        public string clmtmp_last_action_date { get; set; }
    }
}
