//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerrorismLevy_Zones
    {
        public int TL_Id { get; set; }
        public string TL_Postcode { get; set; }
        public string TL_Zone { get; set; }
    }
}
