//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimInsurers
    {
        public TimInsurers()
        {
            this.TimProducts = new HashSet<TimProducts>();
        }
    
        public int TimIns_id { get; set; }
        public string TimIns_created_who { get; set; }
        public System.DateTime TimIns_created_when { get; set; }
        public string TimIns_updated_who { get; set; }
        public Nullable<System.DateTime> TimIns_updated_when { get; set; }
        public string TimIns_name { get; set; }
        public string TimIns_desc { get; set; }
        public Nullable<int> TimIns_sort { get; set; }
        public bool TimIns_inactive { get; set; }
        public Nullable<int> TimIns_insurer_id { get; set; }
        public string TimIns_receiver_id { get; set; }
    
        public virtual entities entities { get; set; }
        public virtual ICollection<TimProducts> TimProducts { get; set; }
    }
}
