//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpHollardReport
    {
        public string record_type { get; set; }
        public string policy_num { get; set; }
        public string risk_num { get; set; }
        public Nullable<int> trans_num { get; set; }
        public string trans_date { get; set; }
        public string @class { get; set; }
        public string product { get; set; }
        public string status { get; set; }
        public string payment_freq { get; set; }
        public string orig_inception_date { get; set; }
        public string commencement_date { get; set; }
        public string expiry_date { get; set; }
        public string eff_start_date { get; set; }
        public string eff_end_date { get; set; }
        public string base_premium { get; set; }
        public string gst_base_premium { get; set; }
        public string sd { get; set; }
        public string fsl { get; set; }
        public string terrorism_tier { get; set; }
        public string terrorism_levy { get; set; }
        public int terrorism_admin_fee { get; set; }
        public int gst_terrorism_admin_fee { get; set; }
        public int terrorism_comm { get; set; }
        public int gst_terrorism_comm { get; set; }
        public string policy_fee { get; set; }
        public string gst_policy_fee { get; set; }
        public int admin_fee { get; set; }
        public int gst_admin_fee { get; set; }
        public int risk_fee { get; set; }
        public int gst_risk_fee { get; set; }
        public int installment_charge { get; set; }
        public int gst_installment_charge { get; set; }
        public int other_fee { get; set; }
        public int gst_other_fee { get; set; }
        public string gross_premium { get; set; }
        public string currency { get; set; }
        public Nullable<int> client_num { get; set; }
        public string insured_fname { get; set; }
        public string insured_sname { get; set; }
        public string insured_org_name { get; set; }
        public string insured_address { get; set; }
        public string insured_suburb { get; set; }
        public string insured_state { get; set; }
        public string insured_postcode { get; set; }
        public string insured_country { get; set; }
        public string risk_address { get; set; }
        public string risk_suburb { get; set; }
        public string risk_state { get; set; }
        public string risk_postcode { get; set; }
        public string risk_country { get; set; }
        public string broker_comm { get; set; }
        public string gst_broker_comm { get; set; }
        public string broker_terms { get; set; }
        public string broker { get; set; }
        public string underwriter { get; set; }
        public string excess { get; set; }
        public string fac_cover_flag { get; set; }
        public int gst_itc_rate { get; set; }
        public string total_sum_insured { get; set; }
        public string benefit1 { get; set; }
        public string sum_insured1 { get; set; }
        public string benefit2 { get; set; }
        public string sum_insured2 { get; set; }
        public string benefit3 { get; set; }
        public string sum_insured3 { get; set; }
        public string benefit4 { get; set; }
        public string sum_insured4 { get; set; }
        public string benefit5 { get; set; }
        public string sum_insured5 { get; set; }
        public string anzsic_code { get; set; }
        public Nullable<int> spid { get; set; }
    }
}
