//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_Category
    {
        public TT_Category()
        {
            this.TT_RiskSectionDetail = new HashSet<TT_RiskSectionDetail>();
        }
    
        public int ttcat_id { get; set; }
        public string ttcat_created_who { get; set; }
        public System.DateTime ttcat_created_when { get; set; }
        public string ttcat_updated_who { get; set; }
        public Nullable<System.DateTime> ttcat_updated_when { get; set; }
        public string ttcat_name { get; set; }
        public string ttcat_code { get; set; }
        public Nullable<bool> ttcat_terrorism_levy { get; set; }
        public Nullable<bool> ttcat_gst_exempt { get; set; }
        public string ttcat_label { get; set; }
        public Nullable<int> ttcat_sort { get; set; }
        public bool ttcat_inactive { get; set; }
    
        public virtual ICollection<TT_RiskSectionDetail> TT_RiskSectionDetail { get; set; }
    }
}
