//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_RiskSectionDetail
    {
        public int ttrsd_id { get; set; }
        public int ttrsd_ttrs_id { get; set; }
        public int ttrsd_wor_id { get; set; }
        public int ttrsd_ttcat_id { get; set; }
        public bool ttrsd_terrorism_levy_exempt { get; set; }
        public string ttrsd_description { get; set; }
        public decimal ttrsd_sum_insured { get; set; }
        public Nullable<decimal> ttrsd_rate { get; set; }
        public decimal ttrsd_base_premium { get; set; }
        public decimal ttrsd_terrorism_levy { get; set; }
        public decimal ttrsd_fsl { get; set; }
        public decimal ttrsd_premium_gst { get; set; }
        public decimal ttrsd_stamp_duty { get; set; }
        public decimal ttrsd_gross_premium { get; set; }
        public decimal ttrsd_comm_net_gst { get; set; }
        public decimal ttrsd_comm_gst { get; set; }
        public decimal ttrsd_net_premium { get; set; }
    
        public virtual TT_Category TT_Category { get; set; }
        public virtual TT_RiskSection TT_RiskSection { get; set; }
        public virtual workbooks workbooks { get; set; }
    }
}
