//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_RiskSection
    {
        public TT_RiskSection()
        {
            this.TT_RiskSectionDetail = new HashSet<TT_RiskSectionDetail>();
        }
    
        public int ttrs_id { get; set; }
        public int ttrs_wor_id { get; set; }
        public string ttrs_address_1 { get; set; }
        public string ttrs_address_2 { get; set; }
        public int ttrs_postcode { get; set; }
        public int ttrs_risk_number { get; set; }
    
        public virtual TT_Postcode TT_Postcode { get; set; }
        public virtual workbooks workbooks { get; set; }
        public virtual ICollection<TT_RiskSectionDetail> TT_RiskSectionDetail { get; set; }
    }
}
