//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_Stamp_Duty
    {
        public int ttsd_id { get; set; }
        public string ttsd_created_who { get; set; }
        public System.DateTime ttsd_created_when { get; set; }
        public string ttsd_updated_who { get; set; }
        public Nullable<System.DateTime> ttsd_updated_when { get; set; }
        public string ttsd_name { get; set; }
        public int ttsd_state { get; set; }
        public int ttsd_category { get; set; }
        public Nullable<decimal> ttsd_rate { get; set; }
        public Nullable<System.DateTime> ttsd_effective_date { get; set; }
        public Nullable<int> ttsd_sort { get; set; }
        public bool ttsd_inactive { get; set; }
    
        public virtual states states { get; set; }
    }
}
