//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_TerrorismLevy
    {
        public int tl_id { get; set; }
        public string tl_created_who { get; set; }
        public System.DateTime tl_created_when { get; set; }
        public string tl_updated_who { get; set; }
        public Nullable<System.DateTime> tl_updated_when { get; set; }
        public string tl_tier { get; set; }
        public Nullable<decimal> tl_rate { get; set; }
        public Nullable<System.DateTime> tl_effective_date { get; set; }
        public Nullable<int> tl_sort { get; set; }
        public bool tl_inactive { get; set; }
    }
}
