//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class turnoverdetail
    {
        public Nullable<decimal> minval { get; set; }
        public Nullable<decimal> maxval { get; set; }
        public Nullable<decimal> IndCounter { get; set; }
        public Nullable<decimal> OrgCounter { get; set; }
        public int ent_id { get; set; }
        public string ent_name { get; set; }
        public Nullable<decimal> spid { get; set; }
    }
}
