//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserConfig_bak
    {
        public int nUserConfigId { get; set; }
        public string strUsername { get; set; }
        public Nullable<int> nSalesTeam { get; set; }
        public Nullable<int> nSalesTeamOverride { get; set; }
        public Nullable<int> nServiceTeam { get; set; }
        public Nullable<int> nServiceTeamOverride { get; set; }
        public Nullable<int> nBrokerRep { get; set; }
        public Nullable<int> nBrokerRepOverride { get; set; }
        public Nullable<int> nAccountType { get; set; }
        public Nullable<int> nAccountTypeOverride { get; set; }
        public Nullable<int> nDefaultSearch { get; set; }
        public Nullable<int> nNumPerPanelTasks { get; set; }
        public Nullable<int> nWithinDaysTasks { get; set; }
        public Nullable<int> nPopupReminder { get; set; }
        public Nullable<int> nPopupFrequency { get; set; }
        public Nullable<int> nShowPoliciesDue { get; set; }
        public Nullable<int> nNumPerPanelPol { get; set; }
        public Nullable<int> nWithinDaysPol { get; set; }
        public Nullable<int> nShowOutstandingDebt { get; set; }
        public Nullable<int> nNumPerPanelOD { get; set; }
        public Nullable<int> nDaysOverdueOD { get; set; }
        public Nullable<int> nEntityRole { get; set; }
        public Nullable<int> nBranch { get; set; }
        public Nullable<int> nClassification { get; set; }
        public Nullable<int> nEntityRoleOverride { get; set; }
        public Nullable<int> nBranchOverride { get; set; }
        public Nullable<int> nClassificationOverride { get; set; }
        public Nullable<int> nShowTransactionsOutside { get; set; }
        public Nullable<int> nWithinDaysTranOut { get; set; }
        public Nullable<int> nAdvanceQueueManagement { get; set; }
        public Nullable<int> nAllowReopeningTask { get; set; }
        public Nullable<int> nAllowReopeningClaims { get; set; }
        public Nullable<int> nCloseTaskByWindow { get; set; }
        public Nullable<int> nCloseTaskByClose { get; set; }
        public Nullable<int> nAccessBankDetails { get; set; }
        public Nullable<int> nAmendBankDetails { get; set; }
    }
}
