//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class window_security_types
    {
        public int winsecty_id { get; set; }
        public string winsecty_created_who { get; set; }
        public System.DateTime winsecty_created_when { get; set; }
        public string winsecty_updated_who { get; set; }
        public Nullable<System.DateTime> winsecty_updated_when { get; set; }
        public string winsecty_name { get; set; }
        public string winsecty_desc { get; set; }
        public Nullable<int> winsecty_sort { get; set; }
        public bool winsecty_inactive { get; set; }
    }
}
