//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkbookMappings_Insurer
    {
        public int inworma_id { get; set; }
        public string inworma_name { get; set; }
        public int inworma_wor_format { get; set; }
        public Nullable<int> inworma_asic_type { get; set; }
    
        public virtual CustomWorkbooks CustomWorkbooks { get; set; }
        public virtual dofi_types dofi_types { get; set; }
    }
}
