//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkbookMappings_Client
    {
        public int clworma_id { get; set; }
        public string clworma_name { get; set; }
        public Nullable<int> clworma_account_type { get; set; }
        public Nullable<int> clworma_branch { get; set; }
        public Nullable<int> clworma_broker_rep { get; set; }
        public Nullable<int> clworma_sales_team { get; set; }
        public Nullable<int> clworma_service_team { get; set; }
        public Nullable<int> clworma_classification { get; set; }
        public Nullable<int> clworma_source { get; set; }
        public Nullable<int> clworma_structure { get; set; }
        public Nullable<int> clworma_role_type { get; set; }
        public Nullable<int> clworma_client_type { get; set; }
        public int clworma_wor_format { get; set; }
    
        public virtual branches branches { get; set; }
        public virtual client_account_types client_account_types { get; set; }
        public virtual client_classifications client_classifications { get; set; }
        public virtual CustomWorkbooks CustomWorkbooks { get; set; }
        public virtual entities entities { get; set; }
        public virtual organisation_structures organisation_structures { get; set; }
        public virtual sales_teams sales_teams { get; set; }
        public virtual service_teams service_teams { get; set; }
        public virtual sources_of_business sources_of_business { get; set; }
    }
}
