//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkbookMappings_Policy
    {
        public int pworma_id { get; set; }
        public string pworma_name { get; set; }
        public int pworma_wor_format { get; set; }
        public Nullable<int> pworma_branch { get; set; }
        public Nullable<int> pworma_brokerRep { get; set; }
        public Nullable<int> pworma_classOfBusiness { get; set; }
        public Nullable<int> pworma_insurer { get; set; }
    }
}
