//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkbookMappings_PolicyTask
    {
        public int ptworma_id { get; set; }
        public string ptworma_name { get; set; }
        public int ptworma_wor_format { get; set; }
        public Nullable<int> ptworma_branch { get; set; }
        public Nullable<int> ptworma_brokerRep { get; set; }
        public Nullable<int> ptworma_classOfBusiness { get; set; }
        public Nullable<int> ptworma_insurer { get; set; }
        public Nullable<int> ptworma_policyTaskType { get; set; }
    }
}
