//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workbook_Perticulars
    {
        public int wp_id { get; set; }
        public int wp_parent_id { get; set; }
        public string wp_created_who { get; set; }
        public System.DateTime wp_created_when { get; set; }
        public string wp_updated_who { get; set; }
        public Nullable<System.DateTime> wp_updated_when { get; set; }
        public byte[] wp_perticulars { get; set; }
    
        public virtual workbooks workbooks { get; set; }
    }
}
