//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class atura_track_config
    {
        public int attra_id { get; set; }
        public string attra_table_name { get; set; }
        public string attra_change_type { get; set; }
        public int attra_row_id { get; set; }
    }
}
