//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class atura_tagvalue
    {
        public atura_tagvalue()
        {
            this.atura_tagrangevalue = new HashSet<atura_tagrangevalue>();
        }
    
        public int attv_id { get; set; }
        public int attv_insert_id { get; set; }
        public int attv_column_id { get; set; }
        public int attv_row_id { get; set; }
        public string attv_tag { get; set; }
        public int attv_index { get; set; }
        public string attv_value { get; set; }
        public string attv_type { get; set; }
    
        public virtual atura_columns atura_columns { get; set; }
        public virtual ICollection<atura_tagrangevalue> atura_tagrangevalue { get; set; }
        public virtual workbooks workbooks { get; set; }
    }
}
