//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class atura_roles
    {
        public int atrol_bit { get; set; }
        public string atrol_name { get; set; }
        public int atrol_sort { get; set; }
        public string atrol_created_who { get; set; }
        public System.DateTime atrol_created_when { get; set; }
        public string atrol_updated_who { get; set; }
        public Nullable<System.DateTime> atrol_updated_when { get; set; }
        public string atrol_desc { get; set; }
        public Nullable<bool> atrol_active { get; set; }
        public Nullable<int> atrol_mutexcl { get; set; }
    }
}
