//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_general_insurance_workbooks
    {
        public int audit_geninswb_id { get; set; }
        public int geninswb_id { get; set; }
        public string geninswb_created_who { get; set; }
        public System.DateTime geninswb_created_when { get; set; }
        public string geninswb_updated_who { get; set; }
        public Nullable<System.DateTime> geninswb_updated_when { get; set; }
        public string geninswb_name { get; set; }
        public string geninswb_desc { get; set; }
        public int geninswb_sort { get; set; }
        public bool geninswb_inactive { get; set; }
        public byte[] geninswb_object { get; set; }
        public Nullable<byte> geninswb_locking { get; set; }
        public Nullable<byte> geninswb_multi_policy { get; set; }
        public string geninswb_email { get; set; }
        public byte[] geninswb_document_object { get; set; }
    }
}
