//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class brokerlink_alerts
    {
        public int broale_id { get; set; }
        public string broale_created_who { get; set; }
        public System.DateTime broale_created_when { get; set; }
        public string broale_updated_who { get; set; }
        public Nullable<System.DateTime> broale_updated_when { get; set; }
        public string broale_name { get; set; }
        public string broale_desc { get; set; }
        public Nullable<int> broale_sort { get; set; }
        public bool broale_inactive { get; set; }
        public string broale_insurer { get; set; }
        public Nullable<int> broale_ref_num { get; set; }
        public Nullable<int> broale_bs_pol_key { get; set; }
        public string broale_db_pol_key { get; set; }
    }
}
