//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class building_area
    {
        public int buiare_id { get; set; }
        public string buiare_created_who { get; set; }
        public System.DateTime buiare_created_when { get; set; }
        public string buiare_updated_who { get; set; }
        public Nullable<System.DateTime> buiare_updated_when { get; set; }
        public string buiare_name { get; set; }
        public string buiare_desc { get; set; }
        public Nullable<int> buiare_sort { get; set; }
        public bool buiare_inactive { get; set; }
    }
}
