//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessInterruption
    {
        public int BusinessInterruptionId { get; set; }
        public int WorkbookId { get; set; }
        public Nullable<decimal> GrossIncome { get; set; }
        public Nullable<int> GrossIncomeIndemnityPeriod { get; set; }
        public Nullable<decimal> WeeklyIncome { get; set; }
        public Nullable<int> WeeklyIncomeIndemnityPeriod { get; set; }
        public Nullable<decimal> GrossRentals { get; set; }
        public Nullable<int> GrossRentalsIndemnityPeriod { get; set; }
        public Nullable<decimal> AdditionalIncreasedCosts { get; set; }
        public Nullable<decimal> ReinstatementOfDocuments { get; set; }
        public Nullable<decimal> OustandingAccountsReceivable { get; set; }
        public string Excess { get; set; }
        public Nullable<bool> EndorsementsApply { get; set; }
        public Nullable<int> PremiumId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Endorsements { get; set; }
        public Nullable<bool> Validated { get; set; }
    }
}
