//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessBuildingContents
    {
        public int BusinessBuildingContentsId { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public string ConstructionExternal { get; set; }
        public string ConstructionRoof { get; set; }
        public string ConstructionFloor { get; set; }
        public Nullable<int> NumStoreys { get; set; }
        public Nullable<bool> TownWater { get; set; }
        public Nullable<bool> Extinguishers { get; set; }
        public Nullable<bool> HoseReels { get; set; }
        public Nullable<bool> SmokeDetectors { get; set; }
        public Nullable<bool> ThermalAlarms { get; set; }
        public Nullable<bool> Sprinklers { get; set; }
        public Nullable<decimal> BuildingSI { get; set; }
        public Nullable<decimal> ContentsSI { get; set; }
        public Nullable<decimal> RemovalOfDebrisSI { get; set; }
        public Nullable<decimal> OtherSI1 { get; set; }
        public Nullable<decimal> OtherSI2 { get; set; }
        public Nullable<decimal> AccidentalDamageSI { get; set; }
        public string BasisOfSettlement { get; set; }
        public string Excess { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> PremiumId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Endorsements { get; set; }
        public string OtherProtection { get; set; }
        public Nullable<bool> Validated { get; set; }
        public string OtherSIDesc1 { get; set; }
        public string OtherSIDesc2 { get; set; }
    }
}
