//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class calculation_rates
    {
        public int calrat_id { get; set; }
        public string calrat_created_who { get; set; }
        public System.DateTime calrat_created_when { get; set; }
        public string calrat_updated_who { get; set; }
        public Nullable<System.DateTime> calrat_updated_when { get; set; }
        public string calrat_name { get; set; }
        public string calrat_desc { get; set; }
        public Nullable<int> calrat_sort { get; set; }
        public bool calrat_inactive { get; set; }
        public Nullable<int> calrat_cob { get; set; }
        public Nullable<int> calrat_product { get; set; }
        public Nullable<int> calrat_sub_section { get; set; }
        public Nullable<decimal> calrat_min_premium { get; set; }
        public Nullable<double> calrat_tier_1_rate { get; set; }
        public Nullable<decimal> calrat_tier_1_amount { get; set; }
        public Nullable<double> calrat_tier_2_rate { get; set; }
        public Nullable<decimal> calrat_tier_2_amount { get; set; }
        public Nullable<double> calrat_tier_3_rate { get; set; }
        public Nullable<decimal> calrat_tier_3_amount { get; set; }
        public Nullable<double> calrat_tier_4_rate { get; set; }
        public Nullable<decimal> calrat_tier_4_amount { get; set; }
        public Nullable<double> calrat_tier_5_rate { get; set; }
        public Nullable<decimal> calrat_tier_5_amount { get; set; }
        public Nullable<double> calrat_tier_6_rate { get; set; }
        public Nullable<decimal> calrat_tier_6_amount { get; set; }
        public Nullable<double> calrat_tier_7_rate { get; set; }
        public Nullable<decimal> calrat_tier_7_amount { get; set; }
        public Nullable<double> calrat_tier_8_rate { get; set; }
        public Nullable<decimal> calrat_tier_8_amount { get; set; }
        public Nullable<double> calrat_tier_9_rate { get; set; }
        public Nullable<decimal> calrat_tier_9_amount { get; set; }
        public Nullable<double> calrat_tier_10_rate { get; set; }
        public Nullable<decimal> calrat_tier_10_amount { get; set; }
        public Nullable<short> calrat_simple_rating { get; set; }
        public Nullable<decimal> calrat_tier_1_limit { get; set; }
        public Nullable<decimal> calrat_tier_2_limit { get; set; }
        public Nullable<decimal> calrat_tier_3_limit { get; set; }
        public Nullable<decimal> calrat_tier_4_limit { get; set; }
        public Nullable<decimal> calrat_tier_5_limit { get; set; }
        public Nullable<decimal> calrat_tier_6_limit { get; set; }
        public Nullable<decimal> calrat_tier_7_limit { get; set; }
        public Nullable<decimal> calrat_tier_8_limit { get; set; }
        public Nullable<decimal> calrat_tier_9_limit { get; set; }
        public Nullable<decimal> calrat_tier_10_limit { get; set; }
    
        public virtual class_of_business_category class_of_business_category { get; set; }
        public virtual risk_sections risk_sections { get; set; }
        public virtual risk_subsections risk_subsections { get; set; }
    }
}
