//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChaserSequences
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ClientAccountTypeId { get; set; }
        public int TransactionTypeId { get; set; }
        public string DateType { get; set; }
        public string ChaserDocument { get; set; }
        public int TaskDueDateFromChaser { get; set; }
        public string QueueDefault { get; set; }
    }
}
