//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim_tagvalues
    {
        public int clatag_id { get; set; }
        public string clatag_created_who { get; set; }
        public System.DateTime clatag_created_when { get; set; }
        public string clatag_updated_who { get; set; }
        public Nullable<System.DateTime> clatag_updated_when { get; set; }
        public string clatag_name { get; set; }
        public string clatag_desc { get; set; }
        public int clatag_sort { get; set; }
        public bool clatag_inactive { get; set; }
    }
}
