//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim_tasks
    {
        public claim_tasks()
        {
            this.Claim_Notes = new HashSet<Claim_Notes>();
            this.claim_sub_tasks = new HashSet<claim_sub_tasks>();
        }
    
        public int clatas_id { get; set; }
        public int clatas_parent_id { get; set; }
        public string clatas_created_who { get; set; }
        public System.DateTime clatas_created_when { get; set; }
        public string clatas_updated_who { get; set; }
        public Nullable<System.DateTime> clatas_updated_when { get; set; }
        public Nullable<int> clatas_duration { get; set; }
        public bool clatas_closed { get; set; }
        public string clatas_initiated_by { get; set; }
        public string clatas_contact_person { get; set; }
        public Nullable<int> clatas_contact_method { get; set; }
        public string clatas_brief_description { get; set; }
        public Nullable<int> clatas_priority { get; set; }
        public Nullable<System.DateTime> clatas_followup_date { get; set; }
        public string clatas_followup_action { get; set; }
        public Nullable<int> clatas_time_spent { get; set; }
        public Nullable<int> clatas_status { get; set; }
        public string clatas_notes { get; set; }
        public Nullable<int> clatas_document_type { get; set; }
        public byte[] clatas_document { get; set; }
        public Nullable<int> clatas_type { get; set; }
        public Nullable<System.DateTime> clatas_date { get; set; }
        public string clatas_queue { get; set; }
        public string clatas_hyperlink { get; set; }
        public Nullable<System.DateTime> clatas_re_open_Date { get; set; }
        public string clatas_re_open_User { get; set; }
        public string clatas_original_que_person { get; set; }
        public string Fname { get; set; }
        public string clatas_document_size { get; set; }
        public Nullable<bool> IsNewTask { get; set; }
        public string clatas_contact_phone { get; set; }
        public string clatas_contact_mobile { get; set; }
        public string clatas_contact_email { get; set; }
    
        public virtual claim_documents claim_documents { get; set; }
        public virtual ICollection<Claim_Notes> Claim_Notes { get; set; }
        public virtual ICollection<claim_sub_tasks> claim_sub_tasks { get; set; }
        public virtual claim_task_status_types claim_task_status_types { get; set; }
        public virtual claim_task_types claim_task_types { get; set; }
        public virtual claims claims { get; set; }
        public virtual contact_methods contact_methods { get; set; }
        public virtual priorities priorities { get; set; }
    }
}
