//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetails_Category1
    {
        public ClientDetails_Category1()
        {
            this.entities = new HashSet<entities>();
        }
    
        public int cdcat1_id { get; set; }
        public string cdcat1_created_who { get; set; }
        public System.DateTime cdcat1_created_when { get; set; }
        public string cdcat1_updated_who { get; set; }
        public Nullable<System.DateTime> cdcat1_updated_when { get; set; }
        public string cdcat1_name { get; set; }
        public string cdcat1_desc { get; set; }
        public int cdcat1_sort { get; set; }
        public bool cdcat1_inactive { get; set; }
    
        public virtual ICollection<entities> entities { get; set; }
    }
}
