//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomTextTableItems
    {
        public int Id { get; set; }
        public int CustomTableItemId { get; set; }
        public string DefaultText { get; set; }
        public string TextAlignment { get; set; }
        public bool Multiline { get; set; }
    
        public virtual CustomTableItems CustomTableItems { get; set; }
    }
}
