//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEFTItemsInError_Custom
    {
        public int deftiiec_id { get; set; }
        public int deftiiec_deft_item_id { get; set; }
        public string deftiiec_description { get; set; }
    
        public virtual DEFTItems DEFTItems { get; set; }
    }
}
