//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EliteExcess
    {
        public int ExcessId { get; set; }
        public int ClassofBusinessId { get; set; }
        public Nullable<decimal> Excess { get; set; }
        public Nullable<bool> DefaultExcess { get; set; }
    
        public virtual class_of_business_category class_of_business_category { get; set; }
    }
}
