//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_ins_wor_documents
    {
        public int giwordoc_id { get; set; }
        public string giwordoc_created_who { get; set; }
        public System.DateTime giwordoc_created_when { get; set; }
        public string giwordoc_updated_who { get; set; }
        public Nullable<System.DateTime> giwordoc_updated_when { get; set; }
        public int giwordoc_parent_id { get; set; }
        public string giwordoc_name { get; set; }
        public string giwordoc_desc { get; set; }
        public int giwordoc_sort { get; set; }
        public bool giwordoc_inactive { get; set; }
        public Nullable<int> giwordoc_document { get; set; }
        public Nullable<int> giwordoc_type { get; set; }
    
        public virtual gen_ins_documents gen_ins_documents { get; set; }
        public virtual gen_ins_wor_doc_types gen_ins_wor_doc_types { get; set; }
        public virtual general_insurance_workbooks general_insurance_workbooks { get; set; }
    }
}
