//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_mtd_balances
    {
        public int glmtd_id { get; set; }
        public int glmtd_glm_month { get; set; }
        public int glmtd_glsl_id { get; set; }
        public Nullable<decimal> glmtd_op_balance { get; set; }
        public Nullable<decimal> glmtd_cur_balance { get; set; }
        public Nullable<decimal> glmtd_dr { get; set; }
        public Nullable<decimal> glmtd_cr { get; set; }
        public Nullable<int> glmtd_glmv_id { get; set; }
        public string glmtd_created_who { get; set; }
        public System.DateTime glmtd_created_when { get; set; }
        public string glmtd_updated_who { get; set; }
        public Nullable<System.DateTime> glmtd_updated_when { get; set; }
    
        public virtual gl_acc_months gl_acc_months { get; set; }
    }
}
