//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPS_Export_List
    {
        public int gps_id { get; set; }
        public string gps_address { get; set; }
        public string gps_addresstype { get; set; }
        public string gps_entityname { get; set; }
        public string gps_longitude { get; set; }
        public string gps_latitude { get; set; }
        public string gps_username { get; set; }
        public string gps_description { get; set; }
    }
}
