//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class liability_codes
    {
        public int liacod_id { get; set; }
        public string liacod_created_who { get; set; }
        public System.DateTime liacod_created_when { get; set; }
        public string liacod_updated_who { get; set; }
        public Nullable<System.DateTime> liacod_updated_when { get; set; }
        public string liacod_name { get; set; }
        public string liacod_desc { get; set; }
        public Nullable<int> liacod_sort { get; set; }
        public bool liacod_inactive { get; set; }
    }
}
