//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_permissions_bak2
    {
        public int nMenuPerId { get; set; }
        public string strUsername { get; set; }
        public string strMenuText { get; set; }
        public string strMenuTag { get; set; }
        public Nullable<int> nCheckedState { get; set; }
    }
}
