//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motor
    {
        public Motor()
        {
            this.MotorAccessory = new HashSet<MotorAccessory>();
            this.MotorSecurity = new HashSet<MotorSecurity>();
        }
    
        public int MotorId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> MotorType { get; set; }
        public Nullable<bool> ConvertedToNewFormat { get; set; }
        public Nullable<int> Year { get; set; }
        public string Make { get; set; }
        public string BodyType { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
        public string NVIC { get; set; }
        public string Rego { get; set; }
        public Nullable<bool> Registered { get; set; }
        public string VIN { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
        public string EngineSize { get; set; }
        public string Extras { get; set; }
        public string Security { get; set; }
        public Nullable<int> OvernightAddressId { get; set; }
        public string FinanceType { get; set; }
        public string FinancedBy { get; set; }
        public string FinanciersAddress { get; set; }
        public string Type { get; set; }
        public string TypeOfCover { get; set; }
        public string SumInsuredType { get; set; }
        public Nullable<decimal> SumInsured { get; set; }
        public Nullable<decimal> SumInsuredLiability { get; set; }
        public string Excess { get; set; }
        public Nullable<bool> ExcessFree { get; set; }
        public Nullable<bool> WindscreenCover { get; set; }
        public Nullable<int> YearLicenced { get; set; }
        public Nullable<int> NCBBaseYear { get; set; }
        public string NCB { get; set; }
        public string DayParkingType { get; set; }
        public string NightParkingType { get; set; }
        public Nullable<int> PremiumId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<bool> ManualOverride { get; set; }
        public Nullable<int> OvernightLocationId { get; set; }
        public string Endorsements { get; set; }
        public string OldData { get; set; }
        public Nullable<bool> Validated { get; set; }
    
        public virtual Premiums Premiums { get; set; }
        public virtual workbooks workbooks { get; set; }
        public virtual ICollection<MotorAccessory> MotorAccessory { get; set; }
        public virtual ICollection<MotorSecurity> MotorSecurity { get; set; }
    }
}
