//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBRCommissions
    {
        public int BrokerRepId { get; set; }
        public int TranId { get; set; }
        public decimal BrokerRepComm { get; set; }
    
        public virtual entities entities { get; set; }
        public virtual transactions transactions { get; set; }
    }
}
