//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalAccident
    {
        public PersonalAccident()
        {
            this.PersonalAccidentPerson = new HashSet<PersonalAccidentPerson>();
        }
    
        public int PersonalAccidentId { get; set; }
        public int WorkbookId { get; set; }
        public Nullable<bool> AmateurFootball { get; set; }
        public Nullable<bool> AmateurWaterSkiing { get; set; }
        public Nullable<bool> Polo { get; set; }
        public Nullable<bool> AmateurAndNonCompetitiveUnderWaterActivities { get; set; }
        public Nullable<bool> AmateurAndNonCompetitiveIceActivities { get; set; }
        public string OtherActivities { get; set; }
        public Nullable<decimal> CapitalBenefitsSI { get; set; }
        public Nullable<int> AccidentalBenefitMaxWeeks { get; set; }
        public Nullable<decimal> AccidentalBenefitAmountPerWeek { get; set; }
        public Nullable<int> AccidentalBenefitExcessPeriod { get; set; }
        public Nullable<bool> EndorsementsApply { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public int PremiumId { get; set; }
        public string Endorsements { get; set; }
        public Nullable<bool> Validated { get; set; }
    
        public virtual workbooks workbooks { get; set; }
        public virtual Premiums Premiums { get; set; }
        public virtual ICollection<PersonalAccidentPerson> PersonalAccidentPerson { get; set; }
    }
}
