//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyHeader_Category3
    {
        public PolicyHeader_Category3()
        {
            this.general_insurance = new HashSet<general_insurance>();
        }
    
        public int phcat3_id { get; set; }
        public string phcat3_created_who { get; set; }
        public System.DateTime phcat3_created_when { get; set; }
        public string phcat3_updated_who { get; set; }
        public Nullable<System.DateTime> phcat3_updated_when { get; set; }
        public string phcat3_name { get; set; }
        public string phcat3_desc { get; set; }
        public int phcat3_sort { get; set; }
        public bool phcat3_inactive { get; set; }
    
        public virtual ICollection<general_insurance> general_insurance { get; set; }
    }
}
