//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class policy_transaction_documents
    {
        public policy_transaction_documents()
        {
            this.soa_classes_of_business = new HashSet<soa_classes_of_business>();
        }
    
        public int poltrado_id { get; set; }
        public string poltrado_created_who { get; set; }
        public System.DateTime poltrado_created_when { get; set; }
        public string poltrado_updated_who { get; set; }
        public Nullable<System.DateTime> poltrado_updated_when { get; set; }
        public int poltrado_parent_id { get; set; }
        public string poltrado_name { get; set; }
        public string poltrado_desc { get; set; }
        public Nullable<int> poltrado_sort { get; set; }
        public bool poltrado_inactive { get; set; }
        public Nullable<int> poltrado_type { get; set; }
        public byte[] poltrado_object { get; set; }
        public bool HasMacros { get; set; }
        public byte[] poltrado_object_eclipse { get; set; }
        public bool poltrado_email_template { get; set; }
    
        public virtual gen_ins_transaction_types gen_ins_transaction_types { get; set; }
        public virtual gen_ins_wor_doc_types gen_ins_wor_doc_types { get; set; }
        public virtual ICollection<soa_classes_of_business> soa_classes_of_business { get; set; }
    }
}
