//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class priorities
    {
        public priorities()
        {
            this.claim_tasks = new HashSet<claim_tasks>();
            this.journals = new HashSet<journals>();
            this.notes = new HashSet<notes>();
            this.tasks = new HashSet<tasks>();
        }
    
        public int pri_id { get; set; }
        public string pri_created_who { get; set; }
        public System.DateTime pri_created_when { get; set; }
        public string pri_updated_who { get; set; }
        public Nullable<System.DateTime> pri_updated_when { get; set; }
        public string pri_name { get; set; }
        public string pri_desc { get; set; }
        public int pri_sort { get; set; }
        public bool pri_inactive { get; set; }
        public Nullable<int> pri_colour { get; set; }
    
        public virtual ICollection<claim_tasks> claim_tasks { get; set; }
        public virtual ICollection<journals> journals { get; set; }
        public virtual ICollection<notes> notes { get; set; }
        public virtual ICollection<tasks> tasks { get; set; }
    }
}
