//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class rb_reports
    {
        public rb_reports()
        {
            this.rb_group_reports = new HashSet<rb_group_reports>();
            this.rb_params = new HashSet<rb_params>();
            this.rb_prm_run = new HashSet<rb_prm_run>();
            this.rb_main = new HashSet<rb_main>();
            this.rb_order = new HashSet<rb_order>();
            this.rb_queries = new HashSet<rb_queries>();
            this.rb_sort = new HashSet<rb_sort>();
        }
    
        public int rbrep_id { get; set; }
        public string rbrep_name { get; set; }
        public string rbrep_title { get; set; }
        public string rbrep_description { get; set; }
        public Nullable<System.DateTime> rbrep_created_on { get; set; }
        public string rbrep_created_by { get; set; }
        public Nullable<System.DateTime> rbrep_updated_on { get; set; }
        public string rbrep_updated_by { get; set; }
        public Nullable<bool> rbrep_cur_clients { get; set; }
        public Nullable<bool> rbrep_cur_workbooks { get; set; }
        public Nullable<bool> rbrep_cur_policies { get; set; }
        public short rbrep_report_type { get; set; }
    
        public virtual ICollection<rb_group_reports> rb_group_reports { get; set; }
        public virtual ICollection<rb_params> rb_params { get; set; }
        public virtual ICollection<rb_prm_run> rb_prm_run { get; set; }
        public virtual ICollection<rb_main> rb_main { get; set; }
        public virtual ICollection<rb_order> rb_order { get; set; }
        public virtual ICollection<rb_queries> rb_queries { get; set; }
        public virtual ICollection<rb_sort> rb_sort { get; set; }
    }
}
