//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportColumns
    {
        public int atcol_id { get; set; }
        public int atcol_attab_id { get; set; }
        public string atcol_name { get; set; }
        public string atcol_caption { get; set; }
        public string atcol_datatype { get; set; }
    }
}
