//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class risk_subsections
    {
        public risk_subsections()
        {
            this.calculation_rates = new HashSet<calculation_rates>();
        }
    
        public int rissub_id { get; set; }
        public string rissub_created_who { get; set; }
        public System.DateTime rissub_created_when { get; set; }
        public string rissub_updated_who { get; set; }
        public Nullable<System.DateTime> rissub_updated_when { get; set; }
        public string rissub_name { get; set; }
        public string rissub_desc { get; set; }
        public Nullable<int> rissub_sort { get; set; }
        public bool rissub_inactive { get; set; }
        public Nullable<int> rissub_risk_section { get; set; }
    
        public virtual ICollection<calculation_rates> calculation_rates { get; set; }
        public virtual risk_sections risk_sections { get; set; }
    }
}
