//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class risk_sections
    {
        public risk_sections()
        {
            this.calculation_rates = new HashSet<calculation_rates>();
            this.farm_excesses = new HashSet<farm_excesses>();
            this.risk_subsections = new HashSet<risk_subsections>();
            this.subsection_rates = new HashSet<subsection_rates>();
        }
    
        public int ris_id { get; set; }
        public string ris_name { get; set; }
        public string ris_created_who { get; set; }
        public System.DateTime ris_created_when { get; set; }
        public string ris_updated_who { get; set; }
        public Nullable<System.DateTime> ris_updated_when { get; set; }
        public int ris_sort { get; set; }
        public bool ris_inactive { get; set; }
        public string ris_description { get; set; }
        public Nullable<int> ris_class_of_business { get; set; }
    
        public virtual ICollection<calculation_rates> calculation_rates { get; set; }
        public virtual ICollection<farm_excesses> farm_excesses { get; set; }
        public virtual gen_ins_classes_of_business gen_ins_classes_of_business { get; set; }
        public virtual ICollection<risk_subsections> risk_subsections { get; set; }
        public virtual ICollection<subsection_rates> subsection_rates { get; set; }
    }
}
