//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_account
    {
        public string acctmp_client_code { get; set; }
        public string acctmp_type_code { get; set; }
        public string acctmp_cross_reference_code { get; set; }
        public string acctmp_name { get; set; }
        public string acctmp_address_1 { get; set; }
        public string acctmp_address_2 { get; set; }
        public string acctmp_address_3 { get; set; }
        public string acctmp_postcode { get; set; }
        public string acctmp_accounting_code { get; set; }
        public string acctmp_industry_code { get; set; }
        public string acctmp_area_code { get; set; }
        public string acctmp_business_phone_no { get; set; }
        public string acctmp_private_phone_no { get; set; }
        public string acctmp_facsimile_no { get; set; }
        public string acctmp_contact_name { get; set; }
        public string acctmp_addressee { get; set; }
        public string acctmp_salutation { get; set; }
        public string acctmp_occupation { get; set; }
        public string acctmp_account_exec_1 { get; set; }
        public string acctmp_account_exec_2 { get; set; }
        public string acctmp_date_of_birth { get; set; }
        public string acctmp_balance_period_1 { get; set; }
        public string acctmp_balance_period_2 { get; set; }
        public string acctmp_balance_period_3 { get; set; }
        public string acctmp_balance_period_4 { get; set; }
        public string acctmp_balance_period_5 { get; set; }
    }
}
