//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMWorkbookHeader
    {
        public int wor_id { get; set; }
        public Nullable<int> Insurer { get; set; }
        public string Insured { get; set; }
        public Nullable<bool> Posted { get; set; }
        public string ECRequestID { get; set; }
        public string TIMStatus { get; set; }
        public string PolicyCategory { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public string TIMRef { get; set; }
        public Nullable<bool> Bound { get; set; }
        public Nullable<bool> Lapsed { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string TIMInsurerName { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<bool> ParticularsDownloaded { get; set; }
    
        public virtual workbooks workbooks { get; set; }
    }
}
