//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserConfigOptions_bak2
    {
        public int nUserConfigOptionId { get; set; }
        public string strUsername { get; set; }
        public string strOption { get; set; }
        public string strOptionId { get; set; }
    }
}
