//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_usage_types
    {
        public int vehusaty_id { get; set; }
        public string vehusaty_created_who { get; set; }
        public System.DateTime vehusaty_created_when { get; set; }
        public string vehusaty_updated_who { get; set; }
        public Nullable<System.DateTime> vehusaty_updated_when { get; set; }
        public string vehusaty_name { get; set; }
        public string vehusaty_desc { get; set; }
        public Nullable<int> vehusaty_sort { get; set; }
        public bool vehusaty_inactive { get; set; }
    }
}
