//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vims_trans_enquiry
    {
        public int glmv_id { get; set; }
        public Nullable<int> glmv_tran_type { get; set; }
        public Nullable<System.DateTime> glmv_date { get; set; }
        public Nullable<System.DateTime> glmv_created_when { get; set; }
        public string glmv_glrs_set { get; set; }
        public Nullable<int> glmv_record_Ref_id { get; set; }
        public string client { get; set; }
        public string insurer_sa { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string tratyp_desc { get; set; }
        public short spid { get; set; }
    }
}
