//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_types
    {
        public address_types()
        {
            this.addresses = new HashSet<addresses>();
        }
    
        public int addtyp_id { get; set; }
        public string addtyp_created_who { get; set; }
        public System.DateTime addtyp_created_when { get; set; }
        public string addtyp_updated_who { get; set; }
        public Nullable<System.DateTime> addtyp_updated_when { get; set; }
        public string addtyp_name { get; set; }
        public string addtyp_desc { get; set; }
        public bool addtyp_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<addresses> addresses { get; set; }
    }
}
