//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class anzic_subdivisions
    {
        public anzic_subdivisions()
        {
            this.anzic_groups = new HashSet<anzic_groups>();
        }
    
        public int anzsubdiv_id { get; set; }
        public string anzsubdiv_code { get; set; }
        public string anzsubdiv_name { get; set; }
        public int anzsubdiv_parent_id { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual anzic_divisions anzic_divisions { get; set; }
        public virtual ICollection<anzic_groups> anzic_groups { get; set; }
    }
}
