//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class anzic_groups
    {
        public anzic_groups()
        {
            this.anzic_classes = new HashSet<anzic_classes>();
        }
    
        public int anzgroup_id { get; set; }
        public string anzgroup_code { get; set; }
        public string anzgroup_name { get; set; }
        public int anzgroup_parent_id { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<anzic_classes> anzic_classes { get; set; }
        public virtual anzic_subdivisions anzic_subdivisions { get; set; }
    }
}
