//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class asicadp106
    {
        public Nullable<int> pol_tran_id { get; set; }
        public string ent_name { get; set; }
        public Nullable<decimal> Payable { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> ASIC106 { get; set; }
        public string type { get; set; }
        public short spid { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
