//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim_status_types
    {
        public claim_status_types()
        {
            this.claims = new HashSet<claims>();
        }
    
        public int clastaty_id { get; set; }
        public string clastaty_created_who { get; set; }
        public System.DateTime clastaty_created_when { get; set; }
        public string clastaty_updated_who { get; set; }
        public Nullable<System.DateTime> clastaty_updated_when { get; set; }
        public string clastaty_name { get; set; }
        public string clastaty_desc { get; set; }
        public bool clastaty_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<claims> claims { get; set; }
    }
}
