//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimPaymentDetails
    {
        public int cladet_id { get; set; }
        public string cladet_created_who { get; set; }
        public System.DateTime cladet_created_when { get; set; }
        public string cladet_updated_who { get; set; }
        public Nullable<System.DateTime> cladet_updated_when { get; set; }
        public string cladet_name { get; set; }
        public string cladet_desc { get; set; }
        public bool cladet_inactive { get; set; }
        public Nullable<int> cladet_claimtype { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ClaimPaymentTypes ClaimPaymentTypes { get; set; }
    }
}
