//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_of_business_category
    {
        public int claofbus_id { get; set; }
        public string claofbus_created_who { get; set; }
        public System.DateTime claofbus_created_when { get; set; }
        public string claofbus_updated_who { get; set; }
        public Nullable<System.DateTime> claofbus_updated_when { get; set; }
        public string claofbus_name { get; set; }
        public string claofbus_desc { get; set; }
        public bool claofbus_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
