//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_of_business
    {
        public int cob_id { get; set; }
        public int cob_parent_id { get; set; }
        public string cob_created_who { get; set; }
        public System.DateTime cob_created_when { get; set; }
        public string cob_updated_who { get; set; }
        public Nullable<System.DateTime> cob_updated_when { get; set; }
        public Nullable<int> cob_duration { get; set; }
        public string cob_notes { get; set; }
        public Nullable<short> cob_days_credit { get; set; }
        public Nullable<short> cob_days_held_covered { get; set; }
        public Nullable<int> cob_class_of_business { get; set; }
        public Nullable<decimal> cob_commission { get; set; }
        public bool cob_auto_pol_number { get; set; }
        public string cob_pol_number_prefix { get; set; }
        public string cob_pol_number_suffix { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual entities entities { get; set; }
        public virtual gen_ins_classes_of_business gen_ins_classes_of_business { get; set; }
    }
}
