//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_insurance_portfolio
    {
        public int cip_id { get; set; }
        public string cip_name { get; set; }
        public string cip_created_who { get; set; }
        public System.DateTime cip_created_when { get; set; }
        public string cip_updated_who { get; set; }
        public Nullable<System.DateTime> cip_updated_when { get; set; }
        public bool cip_inactive { get; set; }
        public string cip_blob_pointer { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
