//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_classifications
    {
        public client_classifications()
        {
            this.profile = new HashSet<profile>();
        }
    
        public int clicla_id { get; set; }
        public string clicla_created_who { get; set; }
        public System.DateTime clicla_created_when { get; set; }
        public string clicla_updated_who { get; set; }
        public Nullable<System.DateTime> clicla_updated_when { get; set; }
        public string clicla_name { get; set; }
        public string clicla_desc { get; set; }
        public bool clicla_inactive { get; set; }
        public Nullable<int> clicla_colour { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<profile> profile { get; set; }
    }
}
