//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBMappings
    {
        public int nHolMapId { get; set; }
        public string strProduct { get; set; }
        public string strCOB { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
