//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class confirmation_of_cover
    {
        public int coc_id { get; set; }
        public string coc_name { get; set; }
        public string coc_created_who { get; set; }
        public System.DateTime coc_created_when { get; set; }
        public string coc_updated_who { get; set; }
        public Nullable<System.DateTime> coc_updated_when { get; set; }
        public bool coc_inactive { get; set; }
        public string coc_blob_pointer { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
