//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditors_ageing_v
    {
        public int bal_entity_id { get; set; }
        public string ENT_NAME { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientName { get; set; }
        public string Gencob_Name { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> NetPremium { get; set; }
        public System.DateTime tran_time { get; set; }
        public System.DateTime Pol_Effective_Date { get; set; }
        public string tran_type { get; set; }
        public int tran_id { get; set; }
        public Nullable<decimal> BAL_AMOUNT { get; set; }
        public int DAYS_BETWEEN { get; set; }
        public Nullable<int> pol_insurer { get; set; }
        public Nullable<int> pol_debtor { get; set; }
        public Nullable<int> pol_sub_agent { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> spid { get; set; }
        public Nullable<int> PROF_SALES_TEAM { get; set; }
        public string saltea_name { get; set; }
        public Nullable<int> PROF_SERVICE_TEAM { get; set; }
        public string sertea_name { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
