//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_settings
    {
        public string username { get; set; }
        public Nullable<int> form_id { get; set; }
        public string var_name { get; set; }
        public string value { get; set; }
        public int id { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
