//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_insurance
    {
        public general_insurance()
        {
            this.claims = new HashSet<claims>();
            this.workbooks = new HashSet<workbooks>();
            this.policies = new HashSet<policies>();
        }
    
        public int genins_id { get; set; }
        public int genins_parent_id { get; set; }
        public string genins_created_who { get; set; }
        public System.DateTime genins_created_when { get; set; }
        public string genins_updated_who { get; set; }
        public Nullable<System.DateTime> genins_updated_when { get; set; }
        public Nullable<int> genins_duration { get; set; }
        public string genins_name { get; set; }
        public string genins_description { get; set; }
        public Nullable<int> genins_class_of_business { get; set; }
        public Nullable<System.DateTime> genins_date_effective { get; set; }
        public Nullable<int> genins_insurer { get; set; }
        public Nullable<bool> genins_is_hidden { get; set; }
        public Nullable<int> genins_nStatus { get; set; }
        public Nullable<int> genins_nType { get; set; }
        public Nullable<System.DateTime> genins_dtFrom { get; set; }
        public Nullable<System.DateTime> genins_dtTo { get; set; }
        public Nullable<System.DateTime> genins_dtStatusChanged { get; set; }
        public string genins_policy_number { get; set; }
        public Nullable<int> genins_status_type { get; set; }
        public Nullable<int> genins_monthly { get; set; }
        public Nullable<int> genins_nopayments { get; set; }
        public Nullable<int> genins_nodeposit { get; set; }
        public Nullable<int> genins_frequency { get; set; }
        public Nullable<bool> genins_bf_inc_deposit { get; set; }
        public Nullable<bool> genins_spread_ap { get; set; }
        public Nullable<bool> genins_spread_rp { get; set; }
        public string genins_notes { get; set; }
        public Nullable<int> genins_underwriter_id { get; set; }
        public Nullable<int> genins_cancellation_reason { get; set; }
        public Nullable<int> genins_Category1 { get; set; }
        public Nullable<int> genins_Category2 { get; set; }
        public Nullable<int> genins_Category3 { get; set; }
        public string genins_svu_status { get; set; }
        public Nullable<int> genins_current_workbook { get; set; }
        public Nullable<bool> genins_is_tim { get; set; }
        public Nullable<int> genins_anzic_code { get; set; }
        public Nullable<bool> genins_sunrise { get; set; }
        public Nullable<bool> genins_is_iclose { get; set; }
        public byte[] RowVersion { get; set; }
        public string genins_insured { get; set; }
        public Nullable<int> genins_current_policy { get; set; }
    
        public virtual anzic_classes anzic_classes { get; set; }
        public virtual ICollection<claims> claims { get; set; }
        public virtual entities entities { get; set; }
        public virtual entities entities1 { get; set; }
        public virtual gen_ins_classes_of_business gen_ins_classes_of_business { get; set; }
        public virtual ICollection<workbooks> workbooks { get; set; }
        public virtual ICollection<policies> policies { get; set; }
        public virtual policies policies1 { get; set; }
        public virtual workbooks workbooks1 { get; set; }
        public virtual PolicyHeader_Category1 PolicyHeader_Category1 { get; set; }
        public virtual PolicyHeader_Category2 PolicyHeader_Category2 { get; set; }
        public virtual PolicyHeader_Category3 PolicyHeader_Category3 { get; set; }
    }
}
