//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_acc_months
    {
        public gl_acc_months()
        {
            this.gl_mtd_balances = new HashSet<gl_mtd_balances>();
            this.gl_movements = new HashSet<gl_movements>();
        }
    
        public int glm_month { get; set; }
        public string glm_open { get; set; }
        public string glm_created_who { get; set; }
        public System.DateTime glm_created_when { get; set; }
        public string glm_updated_who { get; set; }
        public Nullable<System.DateTime> glm_updated_when { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<gl_mtd_balances> gl_mtd_balances { get; set; }
        public virtual ICollection<gl_movements> gl_movements { get; set; }
    }
}
