//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurers_Category3
    {
        public Insurers_Category3()
        {
            this.entities = new HashSet<entities>();
        }
    
        public int incat3_id { get; set; }
        public string incat3_created_who { get; set; }
        public System.DateTime incat3_created_when { get; set; }
        public string incat3_updated_who { get; set; }
        public Nullable<System.DateTime> incat3_updated_when { get; set; }
        public string incat3_name { get; set; }
        public string incat3_desc { get; set; }
        public bool incat3_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<entities> entities { get; set; }
    }
}
