//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel
    {
        public personnel()
        {
            this.categories = new HashSet<categories>();
        }
    
        public int per_id { get; set; }
        public int per_parent_id { get; set; }
        public string per_created_who { get; set; }
        public System.DateTime per_created_when { get; set; }
        public string per_updated_who { get; set; }
        public Nullable<System.DateTime> per_updated_when { get; set; }
        public Nullable<int> per_duration { get; set; }
        public bool per_primary_contact { get; set; }
        public Nullable<int> per_personnel_type { get; set; }
        public string per_addressee { get; set; }
        public string per_salutation { get; set; }
        public string per_job_title { get; set; }
        public string per_telephone { get; set; }
        public string per_telephone_2 { get; set; }
        public string per_mobile { get; set; }
        public string per_facsimile { get; set; }
        public string per_email { get; set; }
        public bool per_newsletter { get; set; }
        public bool per_newsfax { get; set; }
        public Nullable<byte> per_update_flag { get; set; }
        public string per_website { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<categories> categories { get; set; }
        public virtual entities entities { get; set; }
        public virtual personnel_types personnel_types { get; set; }
    }
}
