//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class refunds
    {
        public int ref_id { get; set; }
        public string ref_type { get; set; }
        public Nullable<int> ref_record_ref_id { get; set; }
        public Nullable<int> ref_pay_id { get; set; }
        public string ref_created_who { get; set; }
        public System.DateTime ref_created_when { get; set; }
        public string ref_updated_who { get; set; }
        public Nullable<System.DateTime> ref_updated_when { get; set; }
        public Nullable<decimal> ref_Amount { get; set; }
        public Nullable<decimal> ref_tran_id { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
