//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_teams
    {
        public sales_teams()
        {
            this.profile = new HashSet<profile>();
        }
    
        public int saltea_id { get; set; }
        public string saltea_created_who { get; set; }
        public System.DateTime saltea_created_when { get; set; }
        public string saltea_updated_who { get; set; }
        public Nullable<System.DateTime> saltea_updated_when { get; set; }
        public string saltea_name { get; set; }
        public string saltea_desc { get; set; }
        public bool saltea_inactive { get; set; }
        public string saltea_full_name { get; set; }
        public string saltea_ar_no { get; set; }
        public string saltea_branch_id { get; set; }
        public string saltea_title { get; set; }
        public string saltea_address { get; set; }
        public string saltea_suburb { get; set; }
        public Nullable<int> saltea_state { get; set; }
        public string saltea_postcode { get; set; }
        public string saltea_phone { get; set; }
        public string saltea_mobile { get; set; }
        public string saltea_email { get; set; }
        public string saltea_facsimile { get; set; }
        public string saltea_company_name { get; set; }
        public string saltea_trading_as { get; set; }
        public string saltea_address_2 { get; set; }
        public string saltea_address_3 { get; set; }
        public string saltea_web_site { get; set; }
        public string saltea_ABN { get; set; }
        public string saltea_ACN { get; set; }
        public bool saltea_Use_Billing { get; set; }
        public bool saltea_Use_Closing { get; set; }
        public bool saltea_Use_other { get; set; }
        public bool saltea_Use_statement { get; set; }
        public string saltea_logo { get; set; }
        public string saltea_Data1 { get; set; }
        public string saltea_Data2 { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<profile> profile { get; set; }
        public virtual states states { get; set; }
    }
}
