//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sunrise_instalment_payments
    {
        public int sip_id { get; set; }
        public int sip_sunistal_id { get; set; }
        public Nullable<int> sip_pol_id { get; set; }
        public double sip_no { get; set; }
        public System.DateTime sip_due_date { get; set; }
        public Nullable<System.DateTime> sip_date_to { get; set; }
        public string sip_status { get; set; }
        public string sip_status_desc { get; set; }
        public decimal sip_total_due { get; set; }
        public decimal sip_premium { get; set; }
        public decimal sip_levy { get; set; }
        public decimal sip_duty { get; set; }
        public decimal sip_tax { get; set; }
        public decimal sip_comm { get; set; }
        public decimal sip_comm_tax { get; set; }
        public decimal sip_fee { get; set; }
        public decimal sip_fee_tax { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual sunrise_instalment sunrise_instalment { get; set; }
    }
}
