//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Total_Earnings
    {
        public Nullable<decimal> GrossEarnings { get; set; }
        public Nullable<decimal> GSTOnBrokerEarnings { get; set; }
        public Nullable<decimal> NetBrokerRepEarnings { get; set; }
        public Nullable<decimal> GSTOnBrokerRep { get; set; }
        public Nullable<decimal> PreviouslyPaid { get; set; }
        public short SPID { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
