//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_types
    {
        public transaction_types()
        {
            this.gl_movements = new HashSet<gl_movements>();
            this.transaction_reasons = new HashSet<transaction_reasons>();
            this.transaction_sets = new HashSet<transaction_sets>();
        }
    
        public int tratyp_id { get; set; }
        public string tratyp_created_who { get; set; }
        public System.DateTime tratyp_created_when { get; set; }
        public string tratyp_updated_who { get; set; }
        public Nullable<System.DateTime> tratyp_updated_when { get; set; }
        public string tratyp_name { get; set; }
        public string tratyp_desc { get; set; }
        public bool tratyp_inactive { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<gl_movements> gl_movements { get; set; }
        public virtual ICollection<transaction_reasons> transaction_reasons { get; set; }
        public virtual ICollection<transaction_sets> transaction_sets { get; set; }
    }
}
