//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_items
    {
        public int tritm_tran_id { get; set; }
        public int tritm_entity_id { get; set; }
        public int tritm_led_id { get; set; }
        public Nullable<int> tritm_inc_id { get; set; }
        public Nullable<int> tritm_csh_id { get; set; }
        public decimal tritm_amount { get; set; }
    
        public virtual entities entities { get; set; }
        public virtual transactions transactions { get; set; }
        public virtual transactions transactions1 { get; set; }
        public virtual transactions transactions2 { get; set; }
    }
}
