//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserConfig
    {
        public int nUserConfigId { get; set; }
        public string strUsername { get; set; }
        public Nullable<int> nSalesTeam { get; set; }
        public Nullable<int> nSalesTeamOverride { get; set; }
        public Nullable<int> nServiceTeam { get; set; }
        public Nullable<int> nServiceTeamOverride { get; set; }
        public Nullable<int> nBrokerRep { get; set; }
        public Nullable<int> nBrokerRepOverride { get; set; }
        public Nullable<int> nAccountType { get; set; }
        public Nullable<int> nAccountTypeOverride { get; set; }
        public Nullable<int> nDefaultSearch { get; set; }
        public Nullable<int> nNumPerPanelTasks { get; set; }
        public Nullable<int> nWithinDaysTasks { get; set; }
        public Nullable<int> nPopupReminder { get; set; }
        public Nullable<int> nPopupFrequency { get; set; }
        public Nullable<int> nShowPoliciesDue { get; set; }
        public Nullable<int> nNumPerPanelPol { get; set; }
        public Nullable<int> nWithinDaysPol { get; set; }
        public Nullable<int> nShowOutstandingDebt { get; set; }
        public Nullable<int> nNumPerPanelOD { get; set; }
        public Nullable<int> nDaysOverdueOD { get; set; }
        public Nullable<int> nEntityRole { get; set; }
        public Nullable<int> nBranch { get; set; }
        public Nullable<int> nClassification { get; set; }
        public Nullable<int> nEntityRoleOverride { get; set; }
        public Nullable<int> nBranchOverride { get; set; }
        public Nullable<int> nClassificationOverride { get; set; }
        public Nullable<int> nShowTransactionsOutside { get; set; }
        public Nullable<int> nWithinDaysTranOut { get; set; }
        public Nullable<int> nAdvanceQueueManagement { get; set; }
        public Nullable<int> nAllowReopeningTask { get; set; }
        public Nullable<int> nAllowReopeningClaims { get; set; }
        public Nullable<int> nCloseTaskByWindow { get; set; }
        public Nullable<int> nCloseTaskByClose { get; set; }
        public Nullable<int> nAccessBankDetails { get; set; }
        public Nullable<int> nAmendBankDetails { get; set; }
        public Nullable<int> nAllowUpdateClientTask { get; set; }
        public Nullable<int> nAllowDeleteClientTask { get; set; }
        public Nullable<int> nAllowReOpenClientTask { get; set; }
        public Nullable<int> nAllowUpdateClientNotes { get; set; }
        public Nullable<int> nAllowUpdateClientDOC { get; set; }
        public Nullable<int> nAllowDeleteClientNotes { get; set; }
        public Nullable<int> nAllowDeleteClientDOC { get; set; }
        public Nullable<int> nAllowUpdateClaimTask { get; set; }
        public Nullable<int> nAllowDeleteClaimTask { get; set; }
        public Nullable<int> nAllowReOpenClaimTask { get; set; }
        public Nullable<int> nAllowUpdateClaimNotes { get; set; }
        public Nullable<int> nAllowUpdateClaimDOC { get; set; }
        public Nullable<int> nAllowDeleteClaimNotes { get; set; }
        public Nullable<int> nAllowDeleteClaimDOC { get; set; }
        public Nullable<int> nAllowUpdatePolicyTask { get; set; }
        public Nullable<int> nAllowDeletePolicyTask { get; set; }
        public Nullable<int> nAllowReOpenPolicyTask { get; set; }
        public Nullable<int> nAllowUpdatePolicyNotes { get; set; }
        public Nullable<int> nAllowUpdatePolicyDOC { get; set; }
        public Nullable<int> nAllowDeletePolicyNotes { get; set; }
        public Nullable<int> nAllowDeletePolicyDOC { get; set; }
        public Nullable<int> nSubBranchOverride { get; set; }
        public int nTaskFor { get; set; }
        public Nullable<int> nDisplayIncome { get; set; }
        public Nullable<int> nDisplayGrossIncome { get; set; }
        public Nullable<int> nDisplayNetIncome { get; set; }
        public Nullable<int> nDisplayARIncome { get; set; }
        public string DefaultIncome { get; set; }
        public Nullable<int> nAllowCashReceiptClosingOption { get; set; }
        public string strSVUUsername { get; set; }
        public Nullable<int> nAllowPostedWorkbookUpdate { get; set; }
        public Nullable<int> nValidateBankDetails { get; set; }
        public Nullable<bool> nHideDueTasks { get; set; }
        public string strUserDetailsName { get; set; }
        public string strUserDetailsEmail { get; set; }
        public string strTasksDefaultQueue { get; set; }
        public Nullable<int> nDisplayClaimTasks { get; set; }
        public Nullable<int> nDisplayClientTasks { get; set; }
        public Nullable<int> nDisplayPolicyTasks { get; set; }
        public Nullable<int> nShowOutstandingClaim { get; set; }
        public Nullable<int> nWithinDaysClaim { get; set; }
        public Nullable<int> nShowWorkbooksNotPosted { get; set; }
        public Nullable<int> nWithinDaysWorkbooksNotPosted { get; set; }
        public Nullable<int> nTransTypeQuotation { get; set; }
        public Nullable<int> nTransTypeCoverNotes { get; set; }
        public Nullable<int> nTranTypeLapses { get; set; }
        public Nullable<int> nPanelOrderOutstandingTasks { get; set; }
        public Nullable<int> nPanelOrderOutstandingClaims { get; set; }
        public Nullable<int> nPanelOrderPoliciesForRenewal { get; set; }
        public Nullable<int> nPanelOrderOutstandingDebts { get; set; }
        public Nullable<int> nPanelOrderTransOutsideCreditTermDate { get; set; }
        public Nullable<int> nPanelOrderWorkbooksNotPosted { get; set; }
        public int nAllowDeleteEntity { get; set; }
        public string strVpnFileLocation { get; set; }
        public string strVpnProfileName { get; set; }
        public string strVpnUserName { get; set; }
        public string strVpnPassword { get; set; }
        public bool nAutoConnectVpn { get; set; }
        public Nullable<bool> nShowPriorityBackgroundColours { get; set; }
        public bool nAllowUpdateWorkbookNote { get; set; }
        public bool nAllowDeleteWorkbookNote { get; set; }
        public bool nClaimsUseAllSalesTeams { get; set; }
        public bool nClaimsUseAllBrokerReps { get; set; }
        public bool nClaimsUseAllServiceTeams { get; set; }
        public bool nClaimsUseAllBranches { get; set; }
        public bool nPoliciesUseAllSalesTeams { get; set; }
        public bool nPoliciesUseAllBrokerReps { get; set; }
        public bool nPoliciesUseAllServiceTeams { get; set; }
        public bool nPoliciesUseAllBranches { get; set; }
        public bool nDebtsUseAllSalesTeams { get; set; }
        public bool nDebtsUseAllBrokerReps { get; set; }
        public bool nDebtsUseAllServiceTeams { get; set; }
        public bool nDebtsUseAllBranches { get; set; }
        public bool nInsurersUseAllInsurers { get; set; }
        public bool nInsurersUseAllBranches { get; set; }
        public bool nTIMEnabled { get; set; }
        public bool nICloseEnabled { get; set; }
        public bool nShowPoliciesDueFilter { get; set; }
        public bool nShowOutstandingTask { get; set; }
        public bool nDuePoliciesShowNoTrans { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
