//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOALedgerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebClientSummaryHeaderFields
    {
        public int field_Id { get; set; }
        public string field_name { get; set; }
        public Nullable<bool> field_onlyclient { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
