//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class anzic_divisions
    {
        public anzic_divisions()
        {
            this.anzic_subdivisions = new HashSet<anzic_subdivisions>();
        }
    
        public int anzdiv_id { get; set; }
        public string anzdiv_code { get; set; }
        public string anzdiv_name { get; set; }
    
        public virtual ICollection<anzic_subdivisions> anzic_subdivisions { get; set; }
    }
}
