//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class atura_tables
    {
        public atura_tables()
        {
            this.atura_columns = new HashSet<atura_columns>();
            this.atura_columns1 = new HashSet<atura_columns>();
            this.atura_tables1 = new HashSet<atura_tables>();
            this.CustomDropDownListTableItems = new HashSet<CustomDropDownListTableItems>();
            this.CustomRowTableItems = new HashSet<CustomRowTableItems>();
            this.FrameMaintenanceReferenceTables = new HashSet<FrameMaintenanceReferenceTables>();
        }
    
        public int attab_id { get; set; }
        public string attab_type { get; set; }
        public string attab_name { get; set; }
        public string attab_prefix { get; set; }
        public string attab_caption { get; set; }
        public string attab_singular_caption { get; set; }
        public Nullable<int> attab_roles { get; set; }
        public Nullable<int> attab_parent_id { get; set; }
        public bool attab_new { get; set; }
        public bool attab_object { get; set; }
        public bool attab_protect { get; set; }
        public int attab_unique_colid { get; set; }
        public int attab_sort_colid { get; set; }
        public string attab_icon_path { get; set; }
        public bool attab_closing { get; set; }
        public bool attab_autoclose { get; set; }
        public bool attab_has_queue { get; set; }
        public int attab_sort { get; set; }
        public Nullable<byte> attab_help_type { get; set; }
        public string attab_html_file { get; set; }
        public string attab_html_topic { get; set; }
    
        public virtual ICollection<atura_columns> atura_columns { get; set; }
        public virtual ICollection<atura_columns> atura_columns1 { get; set; }
        public virtual ICollection<atura_tables> atura_tables1 { get; set; }
        public virtual atura_tables atura_tables2 { get; set; }
        public virtual ICollection<CustomDropDownListTableItems> CustomDropDownListTableItems { get; set; }
        public virtual ICollection<CustomRowTableItems> CustomRowTableItems { get; set; }
        public virtual ICollection<FrameMaintenanceReferenceTables> FrameMaintenanceReferenceTables { get; set; }
    }
}
