//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class atura_entity_owner
    {
        public int atown_entity_id { get; set; }
        public string atown_uname { get; set; }
        public int atown_id { get; set; }
    
        public virtual entities entities { get; set; }
    }
}
