//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class body_types
    {
        public int bodtyp_id { get; set; }
        public string bodtyp_created_who { get; set; }
        public System.DateTime bodtyp_created_when { get; set; }
        public string bodtyp_updated_who { get; set; }
        public Nullable<System.DateTime> bodtyp_updated_when { get; set; }
        public string bodtyp_name { get; set; }
        public string bodtyp_desc { get; set; }
        public Nullable<int> bodtyp_sort { get; set; }
        public bool bodtyp_inactive { get; set; }
    }
}
