//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class brokerlink_mail
    {
        public int bromail_id { get; set; }
        public string bromail_created_who { get; set; }
        public System.DateTime bromail_created_when { get; set; }
        public string bromail_updated_who { get; set; }
        public Nullable<System.DateTime> bromail_updated_when { get; set; }
        public string bromail_name { get; set; }
        public string bromail_desc { get; set; }
        public Nullable<int> bromail_sort { get; set; }
        public bool bromail_inactive { get; set; }
        public string bromail_from { get; set; }
        public Nullable<System.DateTime> bromail_date { get; set; }
        public string bromail_message { get; set; }
    }
}
