//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerReps_Category1
    {
        public BrokerReps_Category1()
        {
            this.entities = new HashSet<entities>();
        }
    
        public int brcat1_id { get; set; }
        public string brcat1_created_who { get; set; }
        public System.DateTime brcat1_created_when { get; set; }
        public string brcat1_updated_who { get; set; }
        public Nullable<System.DateTime> brcat1_updated_when { get; set; }
        public string brcat1_name { get; set; }
        public string brcat1_desc { get; set; }
        public int brcat1_sort { get; set; }
        public bool brcat1_inactive { get; set; }
    
        public virtual ICollection<entities> entities { get; set; }
    }
}
