//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class brokerlink_mapping
    {
        public int bromap_id { get; set; }
        public string bromap_created_who { get; set; }
        public System.DateTime bromap_created_when { get; set; }
        public string bromap_updated_who { get; set; }
        public Nullable<System.DateTime> bromap_updated_when { get; set; }
        public string bromap_name { get; set; }
        public string bromap_desc { get; set; }
        public Nullable<int> bromap_sort { get; set; }
        public bool bromap_inactive { get; set; }
        public string bromap_local_name { get; set; }
    }
}
