//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class brokerlink_policies
    {
        public int bropol_id { get; set; }
        public int bropol_parent_id { get; set; }
        public string bropol_created_who { get; set; }
        public System.DateTime bropol_created_when { get; set; }
        public string bropol_updated_who { get; set; }
        public Nullable<System.DateTime> bropol_updated_when { get; set; }
        public Nullable<int> bropol_duration { get; set; }
        public Nullable<int> bropol_pol_ref { get; set; }
        public Nullable<int> bropol_pol_status { get; set; }
        public Nullable<System.DateTime> bropol_timestamp { get; set; }
        public Nullable<int> bropol_bus_status { get; set; }
        public Nullable<int> bropol_cur_stg { get; set; }
        public Nullable<int> bropol_prod_cls_spec { get; set; }
        public string bropol_queue { get; set; }
        public Nullable<byte> bropol_renewal_flag { get; set; }
    
        public virtual policies policies { get; set; }
    }
}
