//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessPolicy
    {
        public int BusinessPolicyId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Description { get; set; }
        public string OccupationCode { get; set; }
        public Nullable<decimal> UnderwriterFee { get; set; }
        public Nullable<decimal> UnderwriterFeeGST { get; set; }
        public string DefaultExcess { get; set; }
        public Nullable<bool> IsfullTermPolicy { get; set; }
    }
}
