//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim_workbooks
    {
        public claim_workbooks()
        {
            this.claims = new HashSet<claims>();
        }
    
        public int clawor_id { get; set; }
        public string clawor_created_who { get; set; }
        public System.DateTime clawor_created_when { get; set; }
        public string clawor_updated_who { get; set; }
        public Nullable<System.DateTime> clawor_updated_when { get; set; }
        public string clawor_name { get; set; }
        public string clawor_desc { get; set; }
        public int clawor_sort { get; set; }
        public bool clawor_inactive { get; set; }
        public byte[] clawor_object { get; set; }
    
        public virtual ICollection<claims> claims { get; set; }
    }
}
