//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomWorkbookTiles
    {
        public CustomWorkbookTiles()
        {
            this.CustomTables = new HashSet<CustomTables>();
        }
    
        public int Id { get; set; }
        public int CustomWorkbookId { get; set; }
        public string Title { get; set; }
        public Nullable<int> TileIndex { get; set; }
        public bool IsMaximised { get; set; }
    
        public virtual ICollection<CustomTables> CustomTables { get; set; }
        public virtual CustomWorkbooks CustomWorkbooks { get; set; }
    }
}
