//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomSumTableItemsItems
    {
        public int Id { get; set; }
        public int CustomSumTableItemId { get; set; }
        public Nullable<int> CustomTableItemId { get; set; }
        public Nullable<int> CustomRowTableItemId { get; set; }
        public Nullable<int> VariableTableItemId { get; set; }
    
        public virtual CustomSumTableItems CustomSumTableItems { get; set; }
    }
}
