//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomWorkbookEntityValues
    {
        public int Id { get; set; }
        public int EntityId { get; set; }
        public string FieldName { get; set; }
        public string Value { get; set; }
    }
}
