//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class dofi_types
    {
        public dofi_types()
        {
            this.WorkbookMappings_Insurer = new HashSet<WorkbookMappings_Insurer>();
        }
    
        public int doftyp_id { get; set; }
        public string doftyp_name { get; set; }
        public string doftyp_code { get; set; }
        public string doftyp_created_who { get; set; }
        public System.DateTime doftyp_created_when { get; set; }
        public string doftyp_updated_who { get; set; }
        public Nullable<System.DateTime> doftyp_updated_when { get; set; }
        public string doftyp_desc { get; set; }
        public Nullable<int> doftyp_sort { get; set; }
        public bool doftyp_inactive { get; set; }
    
        public virtual ICollection<WorkbookMappings_Insurer> WorkbookMappings_Insurer { get; set; }
    }
}
