//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmPropertyBuilding
    {
        public int Id { get; set; }
        public int FarmPropertyId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Year { get; set; }
        public string ExternalWallsConstruction { get; set; }
        public string RoofConstruction { get; set; }
        public Nullable<decimal> SumInsured { get; set; }
        public string Protection { get; set; }
    
        public virtual FarmProperty FarmProperty { get; set; }
    }
}
