//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmPolicy
    {
        public int FarmPolicyId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Description { get; set; }
        public string OccupationCode { get; set; }
        public string DriverExcess21 { get; set; }
        public string DriverExcess22to24 { get; set; }
        public string DriverExcessUndeclared { get; set; }
        public decimal UnderwriterFee { get; set; }
        public decimal UnderwriterFeeGST { get; set; }
        public string DefaultExcess { get; set; }
        public Nullable<decimal> UnderwriterFeeGSTPerc { get; set; }
        public Nullable<bool> IsfullTermPolicy { get; set; }
    }
}
