//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class fund_status
    {
        public fund_status()
        {
            this.fund_batch = new HashSet<fund_batch>();
            this.fund_policies2 = new HashSet<fund_policies2>();
        }
    
        public int status_id { get; set; }
        public string status_desc { get; set; }
        public string status_created_who { get; set; }
        public System.DateTime status_created_when { get; set; }
        public string status_updated_who { get; set; }
        public System.DateTime status_updated_when { get; set; }
    
        public virtual ICollection<fund_batch> fund_batch { get; set; }
        public virtual ICollection<fund_policies2> fund_policies2 { get; set; }
    }
}
