//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_movements
    {
        public gl_movements()
        {
            this.gl_transactions = new HashSet<gl_transactions>();
        }
    
        public int glmv_id { get; set; }
        public System.DateTime glmv_date { get; set; }
        public Nullable<int> glmv_tran_type { get; set; }
        public string glmv_glrs_set { get; set; }
        public string glmv_processed { get; set; }
        public int glmv_glm_month { get; set; }
        public int glmv_record_ref_id { get; set; }
        public string glmv_created_who { get; set; }
        public Nullable<System.DateTime> glmv_created_when { get; set; }
        public string glmv_updated_who { get; set; }
        public Nullable<System.DateTime> glmv_updated_when { get; set; }
    
        public virtual gl_acc_months gl_acc_months { get; set; }
        public virtual transaction_types transaction_types { get; set; }
        public virtual gl_rule_sets gl_rule_sets { get; set; }
        public virtual ICollection<gl_transactions> gl_transactions { get; set; }
    }
}
