//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int loc_id { get; set; }
        public string loc_created_who { get; set; }
        public System.DateTime loc_created_when { get; set; }
        public string loc_updated_who { get; set; }
        public Nullable<System.DateTime> loc_updated_when { get; set; }
        public string loc_name { get; set; }
        public string loc_desc { get; set; }
        public Nullable<int> loc_sort { get; set; }
        public bool loc_inactive { get; set; }
    }
}
