//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class machinery_types
    {
        public int machty_id { get; set; }
        public string machty_created_who { get; set; }
        public System.DateTime machty_created_when { get; set; }
        public string machty_updated_who { get; set; }
        public Nullable<System.DateTime> machty_updated_when { get; set; }
        public string machty_name { get; set; }
        public string machty_desc { get; set; }
        public int machty_sort { get; set; }
        public bool machty_inactive { get; set; }
    }
}
