//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotorAccessory
    {
        public int MotorAccessoryId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> SumInsured { get; set; }
    
        public virtual Motor Motor { get; set; }
    }
}
