//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class pha_ratings
    {
        public pha_ratings()
        {
            this.pha_products = new HashSet<pha_products>();
        }
    
        public int pharat_id { get; set; }
        public string pharat_created_who { get; set; }
        public System.DateTime pharat_created_when { get; set; }
        public string pharat_updated_who { get; set; }
        public Nullable<System.DateTime> pharat_updated_when { get; set; }
        public string pharat_name { get; set; }
        public string pharat_desc { get; set; }
        public Nullable<int> pharat_sort { get; set; }
        public bool pharat_inactive { get; set; }
        public decimal pharat_rating { get; set; }
    
        public virtual ICollection<pha_products> pha_products { get; set; }
    }
}
