//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class rb_queries
    {
        public Nullable<int> rbq_rep_id { get; set; }
        public string rbq_query { get; set; }
        public int rbq_id { get; set; }
    
        public virtual rb_reports rb_reports { get; set; }
    }
}
