//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class states
    {
        public states()
        {
            this.addresses = new HashSet<addresses>();
            this.branches = new HashSet<branches>();
            this.entities = new HashSet<entities>();
            this.sales_teams = new HashSet<sales_teams>();
            this.service_teams = new HashSet<service_teams>();
            this.TT_FSL = new HashSet<TT_FSL>();
            this.TT_Postcode = new HashSet<TT_Postcode>();
            this.TT_Postcode1 = new HashSet<TT_Postcode>();
            this.TT_Stamp_Duty = new HashSet<TT_Stamp_Duty>();
        }
    
        public int sta_id { get; set; }
        public string sta_created_who { get; set; }
        public System.DateTime sta_created_when { get; set; }
        public string sta_updated_who { get; set; }
        public Nullable<System.DateTime> sta_updated_when { get; set; }
        public string sta_name { get; set; }
        public string sta_desc { get; set; }
        public int sta_sort { get; set; }
        public bool sta_inactive { get; set; }
    
        public virtual ICollection<addresses> addresses { get; set; }
        public virtual ICollection<branches> branches { get; set; }
        public virtual ICollection<entities> entities { get; set; }
        public virtual ICollection<sales_teams> sales_teams { get; set; }
        public virtual ICollection<service_teams> service_teams { get; set; }
        public virtual ICollection<TT_FSL> TT_FSL { get; set; }
        public virtual ICollection<TT_Postcode> TT_Postcode { get; set; }
        public virtual ICollection<TT_Postcode> TT_Postcode1 { get; set; }
        public virtual ICollection<TT_Stamp_Duty> TT_Stamp_Duty { get; set; }
    }
}
