//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableAndColumnDescriptions
    {
        public int Id { get; set; }
        public string TableName { get; set; }
        public string TableDescription { get; set; }
        public string ColumnName { get; set; }
        public string ColumnDescription { get; set; }
        public string DataType { get; set; }
        public Nullable<short> MaxLength { get; set; }
        public bool IsForeignKey { get; set; }
        public string UQTableName { get; set; }
        public string UQColumnName { get; set; }
        public bool RequiresDropDownList { get; set; }
    }
}
