//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class third_party_applications
    {
        public int tpa_id { get; set; }
        public int tpa_parent_id { get; set; }
        public string tpa_caption { get; set; }
        public string tpa_path { get; set; }
        public string tpa_arguments { get; set; }
    }
}
