//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_DateVariation
    {
        public int ttdv_id { get; set; }
        public string ttdv_created_who { get; set; }
        public System.DateTime ttdv_created_when { get; set; }
        public string ttdv_updated_who { get; set; }
        public Nullable<System.DateTime> ttdv_updated_when { get; set; }
        public string ttdv_code { get; set; }
        public string ttdv_description { get; set; }
        public Nullable<int> ttdv_sort { get; set; }
        public bool ttdv_inactive { get; set; }
    }
}
