//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_FSL
    {
        public int ttfsl_id { get; set; }
        public string ttfsl_created_who { get; set; }
        public System.DateTime ttfsl_created_when { get; set; }
        public string ttfsl_updated_who { get; set; }
        public Nullable<System.DateTime> ttfsl_updated_when { get; set; }
        public string ttfsl_name { get; set; }
        public int ttfsl_state { get; set; }
        public int ttfsl_category { get; set; }
        public string ttfsl_area { get; set; }
        public Nullable<decimal> ttfsl_rate { get; set; }
        public Nullable<System.DateTime> ttfsl_effective_date { get; set; }
        public Nullable<int> ttfsl_sort { get; set; }
        public bool ttfsl_inactive { get; set; }
    
        public virtual states states { get; set; }
    }
}
