//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConversion.CleanerTool.EclipseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_types
    {
        public int vehty_id { get; set; }
        public string vehty_created_who { get; set; }
        public System.DateTime vehty_created_when { get; set; }
        public string vehty_updated_who { get; set; }
        public Nullable<System.DateTime> vehty_updated_when { get; set; }
        public string vehty_name { get; set; }
        public string vehty_desc { get; set; }
        public int vehty_sort { get; set; }
        public bool vehty_inactive { get; set; }
    }
}
